SELECT * FROM public.user;

DELETE FROM public.user WHERE lname ILIKE 'huxtible';

ALTER TABLE public.user ALTER COLUMN email SET NOT NULL;

ALTER TABLE public.user ADD CONSTRAINT unique_username_address UNIQUE (username); 

SELECT * FROM public.cigars;

CREATE TABLE cigars (
    cigar_id SERIAL,
    cigar VARCHAR,
    length VARCHAR,
    ring_gauge VARCHAR,
    country VARCHAR,
    shape VARCHAR,
    wrapper VARCHAR,
    binder VARCHAR,
    filler VARCHAR,
    color VARCHAR,
    strength VARCHAR,
    start_mfg_yr VARCHAR,
    end_mfg_yr VARCHAR,
    img_url VARCHAR,
    img_cigar VARCHAR,
    mfg_website VARCHAR,
    PRIMARY KEY ( cigar_id )
);

CREATE TABLE cigar_smdb (
    cigar_id SERIAL,
    cigar VARCHAR,
    length VARCHAR,
    ring_gauge VARCHAR,
    country VARCHAR,
    shape VARCHAR,
    wrapper VARCHAR,
    binder VARCHAR,
    filler VARCHAR,
    color VARCHAR,
    strength VARCHAR,
    start_mfg_yr VARCHAR,
    end_mfg_yr VARCHAR,
    img_url VARCHAR,
    img_cigar VARCHAR,
    mfg_website VARCHAR,
    PRIMARY KEY ( cigar_id )
);

DROP TABLE cigars;

INSERT INTO "public"."cigar_smdb" (cigar_id,cigar,length,ring_gauge,country,shape,wrapper,binder,filler,color,strength,start_mfg_yr,end_mfg_yr,img_url,img_cigar,mfg_website) VALUES
    (34867,'Leaf & Bean (For Leaf by Oscar) (see Oscar Valladares)','','','','','','','','','','','','https://iili.io/Hql5me1.png','https://iili.io/Hql5DdB.png',''),
    (41351,'Oscar Valladares 2012 by Oscar Barber Pole (Box Pressed)','6','52','Honduras','Toro','Mexico/Nicaragua','Nicaragua','Honduras/Nicaragua','Multiple','Medium','2018','In Production','https://oscartobacco.com/wp-content/uploads/elementor/thumbs/logo-2012-cn-pab0c7q7g1j2p8a9ryis2nl8m1mxwtgnvc70kla6n8.png','https://oscartobacco.com/wp-content/uploads/barberpoletoro.png','https://oscartobacco.com/'),
    (41352,'Oscar Valladares 2012 by Oscar Barber Pole Lancero 2020','7','38','Honduras','Lancero','Mexico/Shhh, it''s a Secret','Nicaragua','Honduras/Nicaragua','Multiple','Medium','2018','In Production','https://oscartobacco.com/wp-content/uploads/elementor/thumbs/logo-2012-cn-pab0c7q7g1j2p8a9ryis2nl8m1mxwtgnvc70kla6n8.png','https://oscartobacco.com/wp-content/uploads/barberpolelancero.png','https://oscartobacco.com/'),
    (41353,'Oscar Valladares 2012 By Oscar Connecticut Short Robusto','4','54','Honduras','Short Robusto','Connecticut','Honduras','Honduras/Nicaragua','Colorado','Medium','2019','In Production','https://oscartobacco.com/wp-content/uploads/elementor/thumbs/logo-2012-cn-pab0c7q7g1j2p8a9ryis2nl8m1mxwtgnvc70kla6n8.png','https://oscartobacco.com/wp-content/uploads/Short-Robusto-4%C3%9750CN-Fix.png','https://oscartobacco.com/'),
    (41354,'Oscar Valladares 2012 By Oscar Connecticut Sixty','6','60','Honduras','Gordo','Connecticut','Honduras','Honduras/Nicaragua','Colorado','Medium','2019','In Production','https://oscartobacco.com/wp-content/uploads/elementor/thumbs/logo-2012-cn-pab0c7q7g1j2p8a9ryis2nl8m1mxwtgnvc70kla6n8.png','https://oscartobacco.com/wp-content/uploads/Sixty-6%C3%9760CN-Fix.png','https://oscartobacco.com/'),
    (41355,'Oscar Valladares 2012 By Oscar Connecticut Toro','6','52','Honduras','Toro','Connecticut','Honduras','Honduras/Nicaragua','Colorado','Medium','2019','In Production','https://oscartobacco.com/wp-content/uploads/elementor/thumbs/logo-2012-cn-pab0c7q7g1j2p8a9ryis2nl8m1mxwtgnvc70kla6n8.png','https://oscartobacco.com/wp-content/uploads/Toro-6%C3%9752CN-Fix2.png','https://oscartobacco.com/'),
    (41356,'Oscar Valladares 2012 By Oscar Connecticut Torpedo','6','52','Honduras','Torpedo','Connecticut','Honduras','Honduras/Nicaragua','Colorado','Medium','2019','In Production','https://oscartobacco.com/wp-content/uploads/elementor/thumbs/logo-2012-cn-pab0c7q7g1j2p8a9ryis2nl8m1mxwtgnvc70kla6n8.png','https://oscartobacco.com/wp-content/uploads/Torpedo-6.5%C3%9752CN-Fix.png','https://oscartobacco.com/'),
    (41357,'Oscar Valladares 2012 By Oscar Corojo Robusto','5','50','Honduras','Robusto','Corojo/Honduras','Nicaragua','Honduras/Nicaragua','Colorado Maduro','Medium','','','https://oscartobacco.com/wp-content/uploads/elementor/thumbs/logo-2012-cn-pab0c7q7g1j2p8a9ryis2nl8m1mxwtgnvc70kla6n8.png','https://iili.io/Hql5DdB.png','https://oscartobacco.com/'),
    (41358,'Oscar Valladares 2012 By Oscar Corojo Short Robusto','4','54','Honduras','Short Robusto','Corojo/Honduras','Nicaragua','Honduras/Nicaragua','Colorado Maduro','Medium','2018','In Production','https://oscartobacco.com/wp-content/uploads/elementor/thumbs/logo-2012-cn-pab0c7q7g1j2p8a9ryis2nl8m1mxwtgnvc70kla6n8.png','https://oscartobacco.com/wp-content/uploads/Short-Robusto-4%C3%9750CR-Fix.png','https://oscartobacco.com/'),
    (41359,'Oscar Valladares 2012 By Oscar Corojo Sixty','6','60','Honduras','Gordo','Corojo/Honduras','Nicaragua','Honduras/Nicaragua','Colorado Maduro','Medium','2018','In Production','https://oscartobacco.com/wp-content/uploads/elementor/thumbs/logo-2012-cn-pab0c7q7g1j2p8a9ryis2nl8m1mxwtgnvc70kla6n8.png','https://oscartobacco.com/wp-content/uploads/Sixty-6%C3%9760CR-Fix.png','https://oscartobacco.com/'),
    (41360,'Oscar Valladares 2012 By Oscar Corojo Toro','6','52','Honduras','Toro','Corojo/Honduras','Nicaragua','Honduras/Nicaragua','Colorado Claro','Medium','2018','In Production','https://oscartobacco.com/wp-content/uploads/elementor/thumbs/logo-2012-cn-pab0c7q7g1j2p8a9ryis2nl8m1mxwtgnvc70kla6n8.png','https://oscartobacco.com/wp-content/uploads/Toro-6%C3%9752CR-Fix-2.png','https://oscartobacco.com/'),
    (41361,'Oscar Valladares 2012 By Oscar Corojo Torpedo','6','52','Honduras','Torpedo','Corojo/Honduras','Nicaragua','Honduras/Nicaragua','Colorado Maduro','Medium','2018','In Production','https://oscartobacco.com/wp-content/uploads/elementor/thumbs/logo-2012-cn-pab0c7q7g1j2p8a9ryis2nl8m1mxwtgnvc70kla6n8.png','https://oscartobacco.com/wp-content/uploads/Torpedo-6.5%C3%9752CR-Fix-2.png','https://oscartobacco.com/'),
    (41362,'Oscar Valladares 2012 By Oscar Maduro Short Robusto','4','54','Honduras','Short Robusto','Mexico','Honduras','Honduras/Nicaragua','Maduro','Medium','2018','In Production','https://oscartobacco.com/wp-content/uploads/elementor/thumbs/logo-2012-cn-pab0c7q7g1j2p8a9ryis2nl8m1mxwtgnvc70kla6n8.png','https://oscartobacco.com/wp-content/uploads/Short-Robusto-4%C3%9750MD-Fix.png','https://oscartobacco.com/'),
    (41363,'Oscar Valladares 2012 By Oscar Maduro Sixty','6','60','Honduras','Gordo','Mexico','Honduras','Honduras/Nicaragua','Maduro','Medium','2018','In Production','https://oscartobacco.com/wp-content/uploads/elementor/thumbs/logo-2012-cn-pab0c7q7g1j2p8a9ryis2nl8m1mxwtgnvc70kla6n8.png','https://oscartobacco.com/wp-content/uploads/Sixty-6%C3%9760MD-Fix.png','https://oscartobacco.com/'),
    (41364,'Oscar Valladares 2012 By Oscar Maduro Toro','6','52','Honduras','Toro','Mexico','Honduras','Honduras/Nicaragua','Maduro','Medium','2018','In Production','https://oscartobacco.com/wp-content/uploads/elementor/thumbs/logo-2012-cn-pab0c7q7g1j2p8a9ryis2nl8m1mxwtgnvc70kla6n8.png','https://oscartobacco.com/wp-content/uploads/Toro-6%C3%9752-Fix-2.png','https://oscartobacco.com/'),
    (41365,'Oscar Valladares 2012 By Oscar Maduro Torpedo','6','52','Honduras','Torpedo','Mexico','Honduras','Honduras/Nicaragua','Maduro','Medium','2018','In Production','https://oscartobacco.com/wp-content/uploads/elementor/thumbs/logo-2012-cn-pab0c7q7g1j2p8a9ryis2nl8m1mxwtgnvc70kla6n8.png','https://oscartobacco.com/wp-content/uploads/2012-Maduro-Torpedo.png','https://oscartobacco.com/'),
    (41366,'Oscar Valladares Big Johnny','8','66','Honduras','Gordo','Nicaragua','Honduras','Honduras','Maduro','Medium','','','https://iili.io/Hql5me1.png','https://iili.io/Hql5DdB.png','https://oscartobacco.com/'),
    (41367,'Oscar Valladares Ciseron Edition','6','52','Honduras','','Ecuador','Nicaragua','Nicaragua','Colorado','Medium-Full','','','https://oscartobacco.com/wp-content/uploads/elementor/thumbs/logo-ciseron2-pab0fkzeatrtncmz4rl9kzw7fsripj7ebi2upth2vk.png','https://iili.io/Hql5DdB.png','https://oscartobacco.com/'),
    (41368,'Oscar Valladares Leaf by Oscar Altar Q','6','52','Honduras','','Sumatra','Honduras','Honduras','Colorado','Medium','2018','In Production','https://oscartobacco.com/wp-content/uploads/elementor/thumbs/logo-altarq-pab0cx3v6hvqzeo4p6l28gouz71kdkvolzcsla7ouw.png','https://iili.io/Hql5DdB.png','https://oscartobacco.com/'),
    (41369,'Oscar Valladares Leaf by Oscar Cinco Maduro Sixty','6','60','Honduras','Sixty','Nicaragua','Honduras','Costa Rica/Mexico/Nicaragua','Maduro','Medium-Full','','','https://oscartobacco.com/wp-content/uploads/elementor/thumbs/logo-leaf-pab0c6se8aihaqz6zpv4dc8gjgdiltck5utee2he84.png','https://iili.io/Hql5DdB.png','https://oscartobacco.com/'),
    (41370,'Oscar Valladares Leaf by Oscar Cinco Maduro Toro','6','50','Honduras','Toro','Nicaragua','Honduras','Costa Rica/Mexico/Nicaragua','Maduro','Medium-Full','','','https://oscartobacco.com/wp-content/uploads/elementor/thumbs/logo-leaf-pab0c6se8aihaqz6zpv4dc8gjgdiltck5utee2he84.png','https://iili.io/Hql5DdB.png','https://oscartobacco.com/'),
    (41371,'Oscar Valladares Leaf by Oscar Cinco Maduro Torpedo','6.5','50','Honduras','Torpedo','Nicaragua','Honduras','Costa Rica/Mexico/Nicaragua','Maduro','Medium-Full','','','https://oscartobacco.com/wp-content/uploads/elementor/thumbs/logo-leaf-pab0c6se8aihaqz6zpv4dc8gjgdiltck5utee2he84.png','https://iili.io/Hql5DdB.png','https://oscartobacco.com/'),
    (41372,'Oscar Valladares Leaf by Oscar Connecticut 6x60','6','60','Honduras','6x60','Honduras Connecticut','Honduras','Honduras','Colorado Claro','Mild-Medium','2017','In Production','https://oscartobacco.com/wp-content/uploads/elementor/thumbs/logo-leaf-pab0c6se8aihaqz6zpv4dc8gjgdiltck5utee2he84.png','https://iili.io/Hql5DdB.png','https://oscartobacco.com/'),
    (41373,'Oscar Valladares Leaf by Oscar Connecticut Lancero','7','38','Honduras','Lancero','Honduras Connecticut','Honduras','Honduras','Colorado Claro','Mild-Medium','2017','In Production','https://oscartobacco.com/wp-content/uploads/elementor/thumbs/logo-leaf-pab0c6se8aihaqz6zpv4dc8gjgdiltck5utee2he84.png','https://iili.io/Hql5DdB.png','https://oscartobacco.com/'),
    (41374,'Oscar Valladares Leaf by Oscar Connecticut Robusto','5','50','Honduras','Robusto','Honduras Connecticut','Honduras','Honduras','Colorado Claro','Mild-Medium','2017','In Production','https://oscartobacco.com/wp-content/uploads/elementor/thumbs/logo-leaf-pab0c6se8aihaqz6zpv4dc8gjgdiltck5utee2he84.png','https://iili.io/Hql5DdB.png','https://oscartobacco.com/'),
    (41375,'Oscar Valladares Leaf by Oscar Connecticut Toro','6','52','Honduras','Toro','Honduras Connecticut','Honduras','Honduras','Colorado Claro','Mild-Medium','2017','In Production','https://oscartobacco.com/wp-content/uploads/elementor/thumbs/logo-leaf-pab0c6se8aihaqz6zpv4dc8gjgdiltck5utee2he84.png','https://iili.io/Hql5DdB.png','https://oscartobacco.com/'),
    (41376,'Oscar Valladares Leaf by Oscar Connecticut Torpedo','6.5','52','Honduras','Torpedo','Honduras Connecticut','Honduras','Honduras','Colorado Claro','Mild-Medium','2017','In Production','https://oscartobacco.com/wp-content/uploads/elementor/thumbs/logo-leaf-pab0c6se8aihaqz6zpv4dc8gjgdiltck5utee2he84.png','https://iili.io/Hql5DdB.png','https://oscartobacco.com/'),
    (41377,'Oscar Valladares Leaf by Oscar Corojo 6x60','6','60','Honduras','Gordo','Honduras Corojo','Honduras','Honduras','Colorado','Medium','2017','In Production','https://oscartobacco.com/wp-content/uploads/elementor/thumbs/logo-leaf-pab0c6se8aihaqz6zpv4dc8gjgdiltck5utee2he84.png','https://iili.io/Hql5DdB.png','https://oscartobacco.com/'),
    (41378,'Oscar Valladares Leaf by Oscar Corojo Lancero','7','38','Honduras','Lancero','Honduras Corojo','Honduras','Honduras','Colorado','Medium','2017','In Production','https://oscartobacco.com/wp-content/uploads/elementor/thumbs/logo-leaf-pab0c6se8aihaqz6zpv4dc8gjgdiltck5utee2he84.png','https://iili.io/Hql5DdB.png','https://oscartobacco.com/'),
    (41379,'Oscar Valladares Leaf by Oscar Corojo Robusto','5','50','Honduras','Robusto','Honduras Corojo','Honduras','Honduras','Colorado','Medium','2017','In Production','https://oscartobacco.com/wp-content/uploads/elementor/thumbs/logo-leaf-pab0c6se8aihaqz6zpv4dc8gjgdiltck5utee2he84.png','https://iili.io/Hql5DdB.png','https://oscartobacco.com/'),
    (41380,'Oscar Valladares Leaf by Oscar Corojo Toro','6','52','Honduras','Toro','Honduras Corojo','Honduras','Honduras','Colorado','Medium','2017','In Production','https://oscartobacco.com/wp-content/uploads/elementor/thumbs/logo-leaf-pab0c6se8aihaqz6zpv4dc8gjgdiltck5utee2he84.png','https://iili.io/Hql5DdB.png','https://oscartobacco.com/'),
    (41381,'Oscar Valladares Leaf by Oscar Corojo Torpedo','6.5','52','Honduras','Torpedo','Honduras Corojo','Honduras','Honduras','Colorado','Medium','2017','In Production','https://oscartobacco.com/wp-content/uploads/elementor/thumbs/logo-leaf-pab0c6se8aihaqz6zpv4dc8gjgdiltck5utee2he84.png','https://iili.io/Hql5DdB.png','https://oscartobacco.com/'),
    (41382,'Oscar Valladares Leaf by Oscar Maduro 6x60','6','60','Honduras','Gordo','Nicaragua Jalapa','Honduras','Honduras','Maduro','Medium-Full','2017','In Production','https://oscartobacco.com/wp-content/uploads/elementor/thumbs/logo-leaf-pab0c6se8aihaqz6zpv4dc8gjgdiltck5utee2he84.png','https://iili.io/Hql5DdB.png','https://oscartobacco.com/'),
    (41383,'Oscar Valladares Leaf by Oscar Maduro Lancero','7','38','Honduras','Lancero','Nicaragua Jalapa','Honduras','Honduras','Maduro','Medium-Full','2017','In Production','https://oscartobacco.com/wp-content/uploads/elementor/thumbs/logo-leaf-pab0c6se8aihaqz6zpv4dc8gjgdiltck5utee2he84.png','https://iili.io/Hql5DdB.png','https://oscartobacco.com/'),
    (41384,'Oscar Valladares Leaf by Oscar Maduro Robusto','5','50','Honduras','Robusto','Nicaragua Jalapa','Honduras','Honduras','Maduro','Medium-Full','2017','In Production','https://oscartobacco.com/wp-content/uploads/elementor/thumbs/logo-leaf-pab0c6se8aihaqz6zpv4dc8gjgdiltck5utee2he84.png','https://iili.io/Hql5DdB.png','https://oscartobacco.com/'),
    (41385,'Oscar Valladares Leaf by Oscar Maduro Toro','6','52','Honduras','Toro','Nicaragua Jalapa','Honduras','Honduras','Maduro','Medium-Full','2017','In Production','https://oscartobacco.com/wp-content/uploads/elementor/thumbs/logo-leaf-pab0c6se8aihaqz6zpv4dc8gjgdiltck5utee2he84.png','https://iili.io/Hql5DdB.png','https://oscartobacco.com/'),
    (41386,'Oscar Valladares Leaf by Oscar Maduro Torpedo','6.5','52','Honduras','Torpedo','Nicaragua Jalapa','Honduras','Honduras','Maduro','Medium-Full','2017','In Production','https://oscartobacco.com/wp-content/uploads/elementor/thumbs/logo-leaf-pab0c6se8aihaqz6zpv4dc8gjgdiltck5utee2he84.png','https://iili.io/Hql5DdB.png','https://oscartobacco.com/'),
    (41387,'Oscar Valladares Leaf by Oscar Sumatra 6x60','6','60','Honduras','Gordo','Equadorian Sumatra','Honduras','Honduras','Colorado','Mild-Medium','2017','In Production','https://oscartobacco.com/wp-content/uploads/elementor/thumbs/logo-leaf-pab0c6se8aihaqz6zpv4dc8gjgdiltck5utee2he84.png','https://iili.io/Hql5DdB.png','https://oscartobacco.com/'),
    (41388,'Oscar Valladares Leaf by Oscar Sumatra Lancero','7','38','Honduras','Lancero','Equadorian Sumatra','Honduras','Honduras','Colorado','Mild-Medium','2017','In Production','https://oscartobacco.com/wp-content/uploads/elementor/thumbs/logo-leaf-pab0c6se8aihaqz6zpv4dc8gjgdiltck5utee2he84.png','https://iili.io/Hql5DdB.png','https://oscartobacco.com/'),
    (41389,'Oscar Valladares Leaf by Oscar Sumatra Robusto','5','50','Honduras','Robusto','Equadorian Sumatra','Honduras','Honduras','Colorado','Mild-Medium','2017','In Production','https://oscartobacco.com/wp-content/uploads/elementor/thumbs/logo-leaf-pab0c6se8aihaqz6zpv4dc8gjgdiltck5utee2he84.png','https://iili.io/Hql5DdB.png','https://oscartobacco.com/'),
    (41390,'Oscar Valladares Leaf by Oscar Sumatra Toro','6','52','Honduras','Toro','Equadorian Sumatra','Honduras','Honduras','Colorado','Mild-Medium','2017','In Production','https://oscartobacco.com/wp-content/uploads/elementor/thumbs/logo-leaf-pab0c6se8aihaqz6zpv4dc8gjgdiltck5utee2he84.png','https://iili.io/Hql5DdB.png','https://oscartobacco.com/'),
    (41391,'Oscar Valladares Leaf by Oscar Sumatra Torpedo','6.5','52','Honduras','Torpedo','Equadorian Sumatra','Honduras','Honduras','Colorado','Mild-Medium','2017','In Production','https://oscartobacco.com/wp-content/uploads/elementor/thumbs/logo-leaf-pab0c6se8aihaqz6zpv4dc8gjgdiltck5utee2he84.png','https://iili.io/Hql5DdB.png','https://oscartobacco.com/'),
    (41392,'Oscar Valladares McFly Churchill','7','48','Honduras','Churchill','Mexico','Honduras','Dominican Republic/Honduras/Nicaragua','Colorado','Full','2021','In Production','https://oscartobacco.com/wp-content/uploads/elementor/thumbs/Logo-McFly-pk30tfse11yyeczwflgb8ie72rxjgx2ef5dn7egfrw.jpg','https://oscartobacco.com/wp-content/uploads/McFly-Churchill.png','https://oscartobacco.com/'),
    (41393,'Oscar Valladares McFly Sixty','6','60','Honduras','Gordo','Mexico','Honduras','Dominican Republic/Honduras/Nicaragua','Colorado','Full','2021','In Production','https://oscartobacco.com/wp-content/uploads/elementor/thumbs/Logo-McFly-pk30tfse11yyeczwflgb8ie72rxjgx2ef5dn7egfrw.jpg','https://oscartobacco.com/wp-content/uploads/McFly-Sixty.png','https://oscartobacco.com/'),
    (41394,'Oscar Valladares McFly Toro','6','52','Honduras','Toro','Mexico','Honduras','Dominican Republic/Honduras/Nicaragua','Colorado','Full','2021','In Production','https://oscartobacco.com/wp-content/uploads/elementor/thumbs/Logo-McFly-pk30tfse11yyeczwflgb8ie72rxjgx2ef5dn7egfrw.jpg','https://oscartobacco.com/wp-content/uploads/McFly-Toro.png','https://oscartobacco.com/'),
    (41395,'Oscar Valladares My Way By Bayron Duarte Gordito','4','60','Nicaragua','Gordito','Mexico','','Honduras/Nicaragua','Colorado Maduro','Medium-Full','','','https://iili.io/Hql5me1.png','https://iili.io/Hql5DdB.png','https://oscartobacco.com/'),
    (41396,'Oscar Valladares My Way By Bayron Duarte HD','7','66','Nicaragua','','Mexico','','Honduras/Nicaragua','Colorado Maduro','Medium-Full','','','https://iili.io/Hql5me1.png','https://iili.io/Hql5DdB.png','https://oscartobacco.com/'),
    (41397,'Oscar Valladares My Way By Bayron Duarte Sixty','6','60','Nicaragua','Gordo','Mexico','','Honduras/Nicaragua','Colorado Maduro','Medium-Full','','','https://iili.io/Hql5me1.png','https://iili.io/Hql5DdB.png','https://oscartobacco.com/'),
    (41398,'Oscar Valladares My Way By Bayron Duarte Toro Grande','6','54','Nicaragua','Toro Grande','Mexico','','Honduras/Nicaragua','Colorado Maduro','Medium-Full','','','https://iili.io/Hql5me1.png','https://iili.io/Hql5DdB.png','https://oscartobacco.com/'),
    (41399,'Oscar Valladares Rosalila By Oscar Inframundo Maduro Toro','6','52','Honduras','Toro','Honduras','','Honduras','Maduro','Full','','','https://iili.io/Hql5me1.png','https://iili.io/Hql5DdB.png','https://oscartobacco.com/'),
    (41400,'Oscar Valladares Rosalila By Oscar Mundo Celestial Connecticut Toro','6','52','Honduras','Toro','Connecticut Shade/Honduras','','Honduras','Colorado Claro','Medium-Full','','','https://iili.io/Hql5me1.png','https://iili.io/Hql5DdB.png','https://oscartobacco.com/'),
    (41401,'Oscar Valladares Rosalila By Oscar Mundo Presente Corojo Toro','6','52','Honduras','Toro','Connecticut/Honduras','','Honduras','Rosado','Mild','','','https://iili.io/Hql5me1.png','https://iili.io/Hql5DdB.png','https://oscartobacco.com/'),
    (41402,'Oscar Valladares Super Fly Connecticut Corona','5.25','45','Honduras','Corona','Connecticut Shade/Honduras','Honduras','Dominican Republic/Honduras/Nicaragua','Claro','Mild','','In Production','https://oscartobacco.com/wp-content/uploads/logo-superfly.png','https://oscartobacco.com/wp-content/uploads/SF-Connecticut-Corona.png','https://oscartobacco.com/'),
    (41403,'Oscar Valladares Super Fly Connecticut Toro','6','54','Honduras','Toro','Connecticut Shade/Honduras','Honduras','Dominican Republic/Honduras/Nicaragua','Claro','Mild-Medium','','In Production','https://oscartobacco.com/wp-content/uploads/logo-superfly.png','https://oscartobacco.com/wp-content/uploads/SF-Connecticut-Toro.png','https://oscartobacco.com/'),
    (41404,'Oscar Valladares Super Fly Corona','5.25','45','Honduras','Corona','Mexico','Honduras','Dominican Republic/Honduras/Nicaragua','Maduro','Medium-Full','','In Production','https://oscartobacco.com/wp-content/uploads/logo-superfly.png','https://oscartobacco.com/wp-content/uploads/Corona-5.25-x-45.png','https://oscartobacco.com/'),
    (41405,'Oscar Valladares Super Fly Gordo','6.5','60','Honduras','Gordo','Mexico','Honduras','Dominican Republic/Honduras/Nicaragua','Maduro','Medium-Full','','In Production','https://oscartobacco.com/wp-content/uploads/logo-superfly.png','https://oscartobacco.com/wp-content/uploads/Gordo-6.5-x60-Fix.png','https://oscartobacco.com/'),
    (41406,'Oscar Valladares Super Fly Toro','6','54','Honduras','Toro','Mexico','Honduras','Dominican Republic/Honduras/Nicaragua','Maduro','Medium-Full','','In Production','https://oscartobacco.com/wp-content/uploads/logo-superfly.png','https://oscartobacco.com/wp-content/uploads/Toro-6-x-54.png','https://oscartobacco.com/'),
    (41407,'Oscar Valladares The Oscar Habano Robusto','5','50','Honduras','Robusto','Ecuador/Habano','Honduras','Nicaragua','Colorado Maduro','Medium','2016','In Production','https://oscartobacco.com/wp-content/uploads/elementor/thumbs/logo-theoscar-pab0d2qwbi3gx2fxs90tnf9mji9rnri2mr9pgxzbtk.png','https://oscartobacco.com/wp-content/uploads/Robusto-5%C3%9750-Fix-4.png','https://oscartobacco.com/'),
    (41408,'Oscar Valladares The Oscar Habano Sixty','6','60','Honduras','Gordo','Ecuador/Habano','Honduras','Nicaragua','Colorado','Medium','2016','In Production','https://oscartobacco.com/wp-content/uploads/elementor/thumbs/logo-theoscar-pab0d2qwbi3gx2fxs90tnf9mji9rnri2mr9pgxzbtk.png','https://oscartobacco.com/wp-content/uploads/The-OH_Sixty-6%C3%9760.png','https://oscartobacco.com/'),
    (41409,'Oscar Valladares The Oscar Habano Toro','6','52','Honduras','Toro','Ecuador/Habano','Honduras','Nicaragua','Colorado','Medium','2016','In Production','https://oscartobacco.com/wp-content/uploads/elementor/thumbs/logo-theoscar-pab0d2qwbi3gx2fxs90tnf9mji9rnri2mr9pgxzbtk.png','https://oscartobacco.com/wp-content/uploads/The-OH_Toro-6%C3%9752.png','https://oscartobacco.com/'),
    (41410,'Oscar Valladares The Oscar Habano Winter Edition','5.25','44','Honduras','','Ecuador','Honduras','Honduras/Nicaragua','Colorado Maduro','Medium','','','https://oscartobacco.com/wp-content/uploads/elementor/thumbs/logo-theoscar-pab0d2qwbi3gx2fxs90tnf9mji9rnri2mr9pgxzbtk.png','https://iili.io/Hql5DdB.png','https://oscartobacco.com/'),
    (41411,'Oscar Valladares The Oscar Maduro Sixty','6','60','Nicaragua','Gordo','Mexico','Honduras','Honduras/Nicaragua','Maduro','Medium-Full','2017','In Production','https://oscartobacco.com/wp-content/uploads/elementor/thumbs/logo-theoscar-pab0d2qwbi3gx2fxs90tnf9mji9rnri2mr9pgxzbtk.png','https://oscartobacco.com/wp-content/uploads/The-Oscar-Maduro-Sixty-6%C3%9760-fix.png','https://oscartobacco.com/'),
    (41412,'Oscar Valladares The Oscar Maduro Robusto','5','50','Nicaragua','Robusto','Mexico','Honduras','Honduras/Nicaragua','Maduro','Medium-Full','2017','In Production','https://oscartobacco.com/wp-content/uploads/elementor/thumbs/logo-theoscar-pab0d2qwbi3gx2fxs90tnf9mji9rnri2mr9pgxzbtk.png','https://oscartobacco.com/wp-content/uploads/The-Oscar-Maduro-Robusto-5%C3%9750-fix.png','https://oscartobacco.com/'),
    (41413,'Oscar Valladares The Oscar Maduro Corona','5.25','44','Nicaragua','Corona','Mexico','Honduras','Honduras/Nicaragua','Maduro','Medium-Full','2017','In Production','https://oscartobacco.com/wp-content/uploads/elementor/thumbs/logo-theoscar-pab0d2qwbi3gx2fxs90tnf9mji9rnri2mr9pgxzbtk.png','https://oscartobacco.com/wp-content/uploads/The-Oscar-Maduro-Corona-5%C3%9744-fix-copy.png','https://oscartobacco.com/'),
    (41414,'Oscar Valladares The Oscar Maduro Toro','6','52','Nicaragua','Toro','Mexico','Honduras','Honduras/Nicaragua','Maduro','Medium-Full','2017','In Production','https://oscartobacco.com/wp-content/uploads/elementor/thumbs/logo-theoscar-pab0d2qwbi3gx2fxs90tnf9mji9rnri2mr9pgxzbtk.png','https://oscartobacco.com/wp-content/uploads/Toro-6%C3%9752-fix-3.png','https://oscartobacco.com/'),
    (41415,'Oscar Valladares Wild Hunter Natural','6','52','Honduras','','Honduras','Honduras','Honduras','Claro','Medium-Full','2019','In Production','https://oscartobacco.com/wp-content/uploads/elementor/thumbs/logo-wildhunter-pab0batvrxaqc09m6c1t0kasccr1c3topgmw2nss3o.png','https://oscartobacco.com/wp-content/uploads/Wild-Hunter-Natural-Toro-6%C3%9752-Fix.png','https://oscartobacco.com/'),
    (41416,'Oscar Valladares Wild Hunter Oscuro','6','52','Honduras','','Honduras','Honduras','Honduras','Oscuro','Medium-Full','','In Production','https://oscartobacco.com/wp-content/uploads/elementor/thumbs/logo-wildhunter-pab0batvrxaqc09m6c1t0kasccr1c3topgmw2nss3o.png','https://oscartobacco.com/wp-content/uploads/WildHunter-Oscuro-Toro-6%C3%9752-Fix-2.png','https://oscartobacco.com/'),
    (41417,'Oscar Valladares Woody','21','80','Honduras','Extra Gordo','Honduras','Honduras','Honduras/Nicaragua','Maduro','Full','','','https://iili.io/Hql5me1.png','https://iili.io/Hql5DdB.png','https://oscartobacco.com/'),
    (41418,'Oscar Valladares 10th Anniversary Toro','6','52','Honduras','Toro','Dual Wrapper, Mexico San Andres Maduro & Candela','Honduras','Honduras','Maduro & Candela','','','In Production','https://oscartobacco.com/wp-content/uploads/logo-10th-anniversary.jpg','https://oscartobacco.com/wp-content/uploads/10th_0178.png','https://oscartobacco.com/'),
    (41419,'Oscar Valladares 10th Anniversary Sixty','6','60','Honduras','Gordo','Dual Wrapper, Mexico San Andres Maduro & Candela','Honduras','Honduras','Maduro & Candela','','','In Production','https://oscartobacco.com/wp-content/uploads/logo-10th-anniversary.jpg','https://oscartobacco.com/wp-content/uploads/10th_0193.png','https://oscartobacco.com/'),
    (41420,'Oscar Valladares 10th Anniversary Salomon','7','60','Honduras','Salomon','Dual Wrapper, Mexico San Andres Maduro & Candela','Honduras','Honduras','Maduro & Candela','','','In Production','https://oscartobacco.com/wp-content/uploads/logo-10th-anniversary.jpg','https://oscartobacco.com/wp-content/uploads/10th_0185.png','https://oscartobacco.com/'),
    (41421,'Raw Dog by Oscar Valladares','5','60','Honduras','Gordo','None','Honduras','Honduras','Claro','','','In Production','https://oscartobacco.com/wp-content/uploads/elementor/thumbs/logo-rawdog-ov-px11q0pjw41fh5iy2x2mennhiwsg2oulex73048tok.jpg','https://oscartobacco.com/wp-content/uploads/raw_dog_5x60.png','https://oscartobacco.com/');

UPDATE cigars SET country = 'Dominican Republic' WHERE cigar_id = 1;

SELECT * FROM cigars;

