def newString(str):
    alphanumeric = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789'
    newStr = ''
    for s in str:
        if s in alphanumeric:
            newStr += s
    if len(newStr) == 2:
        file1 = open("new_string.txt","a")
        file1.writelines(f"'{str}', {newStr}-00000\n")
        file1.close()
    elif len(newStr) == 3:
        file1 = open("new_string.txt","a")
        file1.writelines(f"'{str}', {newStr}-0000\n")
        file1.close()
    elif len(newStr) == 4:
        file1 = open("new_string.txt","a")
        file1.writelines(f"'{str}', {newStr}-000\n")
        file1.close()
    elif len(newStr) == 5:
        file1 = open("new_string.txt","a")
        file1.writelines(f"'{str}', {newStr}-00\n")
        file1.close()
    elif len(newStr) == 6:
        file1 = open("new_string.txt","a")
        file1.writelines(f"'{str}', {newStr}-0\n")
        file1.close()
    else:
        file1 = open("new_string.txt","a")
        file1.writelines(f"'{str}', {newStr[:7]}-\n")
        file1.close()

newString('100% Dominican')
newString('13 Cigars')
newString('13th Floor')
newString('1502')
newString('1666')
newString('1861')
newString('1876 Reserve')
newString('1881')
newString('1898 Independencia')
newString('20 Minutes')
newString('22N-83W')
newString('262')
newString('3 Reynas')
newString('3x3 (by Occidental, Davidoff)')
newString('420&#39;s')
newString('4x4 (by Occidental, Davidoff)')
newString('5 Vegas')
newString('601 Serie')
newString('708')
newString('7 Brand')
newString('809 (Pride)')
newString('829')
newString('82nd Ave Tobacco &amp; Pipe Ltd')
newString('898 Collection')
newString('Abam')
newString('Abanci')
newString('Abarisco')
newString('Abuelo')
newString('ACID (by Drew Estate)')
newString('Action')
newString('Adante')
newString('Adan y Eva')
newString('Adduci')
newString('Adipati')
newString('Adolphus')
newString('Adrian&#39;s')
newString('A. Fernandez')
newString('A. Flores (by Pinar del Rio)')
newString('Aging Room (by Oliveros)')
newString('Agio')
newString('Aguila')
newString('Aida')
newString('A.J. Fernandez')
newString('AKA (American Kick Ass)')
newString('Alacranes')
newString('Alameda')
newString('Alamo (Finck)')
newString('Albatros')
newString('Albero')
newString('Albion')
newString('Al Capone')
newString('Alcazar')
newString('Aldo')
newString('Alec Bradley')
newString('Alejandro Lopez')
newString('Alfons Mayer')
newString('Alfredo&#39;s Signature Edition')
newString('Alhambra')
newString('Aliados')
newString('All Americas')
newString('Allegria!')
newString('All In!')
newString('Alma Sweets')
newString('Almirante')
newString('Alonso Menendez')
newString('Alta Gracia')
newString('Alternativos')
newString('Alteza')
newString('Alteza Super Premium')
newString('Alvarez Lopez')
newString('Alvaro')
newString('Amati')
newString('Amaya')
newString('Ambiente')
newString('Ambos Mundos')
newString('Ambrosia')
newString('American Born Cubans (La Tradicion Cubana)')
newString('American Eagle')
newString('American Eagles')
newString('American Legion')
newString('American Made')
newString('American Stogies')
newString('American Western')
newString('Amerigo (Thompson)')
newString('Amerino')
newString('Amero')
newString('Amilcar Perez Castro (APC)')
newString('Amish')
newString('Amoroso')
newString('Anacaona')
newString('Ana de Nicaragua')
newString('Ancla y Cazador')
newString('Andiamo')
newString('Andrea&#39;s by Te-Amo')
newString('Andros')
newString('Andujar')
newString('Andulleros')
newString('Angelenos')
newString('Angelina')
newString('Angry Elf')
newString('Anillo de Oro')
newString('Anillo de Plata')
newString('Anna Maria')
newString('Anoranzas')
newString('Antelo')
newString('Antico Cubano')
newString('Antillian')
newString('Antonio Benitez')
newString('Antonio Fermin')
newString('Antonio Gimenez')
newString('Antonio y Cleopatra')
newString('Antonius')
newString('A.O.A.')
newString('A. Pontillo')
newString('Aqua D&#39;T')
newString('Aquarius')
newString('Arabesque')
newString('Arabian Nights')
newString('Arandoza')
newString('Arango')
newString('AR (Armando Ramos)')
newString('Aravega')
newString('Aray &amp; Sons')
newString('Arbol de Palma')
newString('Arc\xc3\xa1ngel Cigars')
newString('Arganese')
newString('Argopuro')
newString('Argyle')
newString('Aristocratas')
newString('Aristocrat by Jose Blanco')
newString('Aristoff')
newString('Arman')
newString('Arnold&#39;s')
newString('Aroma de Cafe')
newString('Aromas de San Andr\xc3\xa9s')
newString('Arsen')
newString('Arte')
newString('Arte Cubano')
newString('Arthur Avenue')
newString('Artigas &amp; Carloni')
newString('Artista')
newString('Artorius')
newString('Arturas Felipe')
newString('Arturo Fuente')
newString('Artus')
newString('Aruba')
newString('Aruhiba')
newString('Arzt de los Reyes')
newString('Ash\xc3\xa9')
newString('Ashford Bentley&#39;s')
newString('Ashton')
newString('Aspira')
newString('Astral')
newString('Asylum')
newString('As You Like It')
newString('Atabey')
newString('A. T. Cofino')
newString('Atlas World Select (Corona Cigar Co.)')
newString('Atocha')
newString('A Traditional Cigar')
newString('A. Turrent')
newString('Augusto Reyes')
newString('Avalon')
newString('Avant Garde (Cornelius &amp; Anthony)')
newString('Avanti')
newString('Ave Maria')
newString('AVO')
newString('Avocado')
newString('Axis')
newString('AZ')
newString('Azan Burgundy (Roberto Duran)')
newString('Azon')
newString('Babalu')
newString('Baccarat')
newString('Bacchus (Thompson)')
newString('Back 9 Cigar Company')
newString('Back Cedarap')
newString('Backgammon')
newString('Backwoods')
newString('Bad Boy Police')
newString('Bad Dog')
newString('Bad Frog')
newString('Badge of Honor')
newString('Bad to the Bone (Outlaw Cigars)')
newString('Bagatelle (Thompson)')
newString('Bahama Mamas')
newString('Bahia')
newString('Bahias')
newString('Bahiba')
newString('Baitoa')
newString('Balboa')
newString('Baldwin')
newString('Balmoral')
newString('Bances')
newString('Bandidos')
newString('Bandoleros')
newString('Bang Bang')
newString('Bar and Books')
newString('Barlovento (Thompson)')
newString('Baron Ullman')
newString('Batey')
newString('Battleground')
newString('Bautismo de Fuego')
newString('Bauza')
newString('Bayamo')
newString('Bayuk')
newString('BB Los Reyes')
newString('Beethoven')
newString('Beldina')
newString('Belice\xc3\xb1o')
newString('Belinda')
newString('Belinda (Cuban)')
newString('Bella Costa')
newString('Bellaterra Ranch')
newString('Bella Torres')
newString('Bellero')
newString('Bello (Cuba Tobacco Cigar Co.)')
newString('Belmondo (Thompson)')
newString('Belmore')
newString('Benavides')
newString('Ben Bey')
newString('Benchmade')
newString('Benedit')
newString('Ben-Hur')
newString('Ben Miguel')
newString('Bentley')
newString('B.E.R.')
newString('Berger &amp; Argenti')
newString('Bering')
newString('Bert Sugar')
newString('Besitos')
newString('Best AL')
newString('Best Buy')
newString('BestCigarPrices.com')
newString('Beverly Hills - VIP')
newString('BG Meyer')
newString('BH Puros')
newString('Biarritz')
newString('Bidwell Blend')
newString('Big Al&#39;s')
newString('Big And Beefy (JR Cigars)')
newString('Big Boys (Two Guys Smoke Shop)')
newString('Big Butt')
newString('Big Chief')
newString('Big City')
newString('Big Dog')
newString('Big Shots')
newString('Bijao')
newString('Biker Boy International')
newString('Biker&#39;s Butt')
newString('Binnys')
newString('Black Abyss')
newString('Black Cat')
newString('Black Crown')
newString('Black Hawk')
newString('Black Label Trading Company')
newString('Black Ops (by K. Hansotia)')
newString('Black Patch')
newString('Black Sheep')
newString('Blackstone')
newString('Black Tie')
newString('Blair')
newString('Blanco (Formerly Los Blancos)')
newString('Blanco y Woermann')
newString('Blanton&#39;s')
newString('Blarney Stone')
newString('Blenders Clearing House')
newString('Blender&#39;s Gold')
newString('Blessed Leaf')
newString('Bloodline')
newString('Blue Banana')
newString('Blue Haze')
newString('Blue Label')
newString('Blue Mountain')
newString('Blue Parrot')
newString('Blue Ribbon Segundos by Drew Estate')
newString('Blue Train')
newString('Bluewater')
newString('Bluntville')
newString('Boardwalk')
newString('Bobalu')
newString('Boca Monte')
newString('Bocanada')
newString('Bock y Ca')
newString('Bodega')
newString('Bodyshot')
newString('Bogar')
newString('Bogey&#39;s Stogies (DR)')
newString('Bogey&#39;s Stogies (Hon)')
newString('Bohemia')
newString('Bohio (Thompson)')
newString('Bolero')
newString('Bolivar')
newString('Bolivar (Cuban)')
newString('Bombs Away (Best Cigar Prices)')
newString('Bonaparte')
newString('Bona Vita')
newString('Bon Bon (Cuba Tobacco Cigar Co.)')
newString('Bonita Smoke Shop')
newString('Boquilla')
newString('Boris 11')
newString('Bossner')
newString('Boston Cigar Factory')
newString('BOTL')
newString('Bottom Shelf')
newString('Bow Tie')
newString('Brahma')
newString('Braniff')
newString('Brasil Autenticos')
newString('Bravados')
newString('Bravo')
newString('Bravo (DR)')
newString('Bravos')
newString('Brazil Tr\xc3\xbcllerie')
newString('Breton')
newString('Breve')
newString('Briarmont')
newString('Brick House')
newString('Brick &amp; Mortar (JR Cigars)')
newString('Brigade (Torano)')
newString('Briones')
newString('Brioso')
newString('Brittania')
newString('Brobergs')
newString('Brocatus')
newString('Brooklyn')
newString('Brun del Re')
newString('Bucanero')
newString('Buckshot')
newString('Buena Vista')
newString('Bufido')
newString('Bugatti (by Perdomo)')
newString('Buho')
newString('Bull City Cigars')
newString('Bulldog')
newString('Bulldog Replacements')
newString('Bundle King')
newString('Bundles')
newString('Burma')
newString('Buscal Buivl')
newString('Bustillo')
newString('Butera')
newString('Byron')
newString('Cabaiguan(by Tatuaje)')
newString('Cabal')
newString('Caballeros')
newString('Cabanas')
newString('Cabanas (Cuban)')
newString('Cabanas y Carbajal')
newString('Cabita')
newString('Cabo Classic')
newString('Cabo Rojo')
newString('Cacique')
newString('Cacique Miami')
newString('Cadenza')
newString('Caiman')
newString('Calderilla')
newString('Calibre 58')
newString('Calixto Lopez')
newString('Calixto Lopez (Nic)')
newString('Calle 8 Ocho')
newString('Calle Ocho')
newString('Callisto')
newString('Camacho')
newString('Camaguey')
newString('Cameroon Giants')
newString('Cameroon Secrets')
newString('Camine Pietro')
newString('Camino Real (by Route 45)')
newString('Caminr Pietro')
newString('Cammarata')
newString('Camos')
newString('Campa')
newString('Campesino')
newString('Campo Verde')
newString('Cana')
newString('Canad')
newString('Canale\xc3\xb1os')
newString('Canaria D&#39;Oro')
newString('Candela')
newString('Candlelight')
newString('Canela')
newString('Caney (Cuban)')
newString('Canimao')
newString('Canonero')
newString('Cantero')
newString('Canuco')
newString('CAO')
newString('Caoba')
newString('Caobanero')
newString('Caonao')
newString('Capadoro')
newString('Capadura')
newString('Capa Fina')
newString('Capa Flor')
newString('Capas')
newString('Capisce')
newString('Capoeira (J. Fuego)')
newString('Capote')
newString('Capricho Cubano')
newString('Captain Black')
newString('Captaris')
newString('Carabana')
newString('Cara Mia')
newString('Carbon Copy')
newString('Carbonell')
newString('Cardenas')
newString('Carey&#39;s')
newString('Caribbean')
newString('Caribbean Dreams')
newString('Caribbean Line')
newString('Caribbean Rounds')
newString('Caribe')
newString('Caribes')
newString('Caridad')
newString('Carillon')
newString('Carinos')
newString('Carl Barrister')
newString('Carlin')
newString('Carlos Evans by Hanlon Ltd')
newString('Carlos III')
newString('Carlos Oliva')
newString('Carlscorona')
newString('Carl Upmann')
newString('Carmelo')
newString('Carmen')
newString('Carmine Pietro')
newString('Carnero')
newString('Carnival Havana')
newString('Carolina Cigar Company')
newString('Carrington')
newString('Cartel Cigars')
newString('Carvelas')
newString('Casa Antero')
newString('Casa Bella (Sindicato Cigars)')
newString('Casa Blanca')
newString('Casa Buena')
newString('Casa Copan')
newString('Casa Cuba (Arturo Fuente)')
newString('Casa Culinaria')
newString('Casada')
newString('Casa de Alegria')
newString('Casa de Diablo')
newString('Casa de Entrada (formerly Cigarcia)')
newString('Casa de Garcia')
newString('Casa del Puro')
newString('Casa de Montecristo')
newString('Casa de Nicaragua')
newString('Casa de Oro')
newString('Casa de Ortez')
newString('Casa de Torres')
newString('Casa Fernandez')
newString('Casa Gomez')
newString('Casa Magna')
newString('Casa Marina')
newString('Casa Miranda')
newString('Casa Montez')
newString('Casa Royale')
newString('Casa Teresa')
newString('Casillas')
newString('Casino Club (Finck)')
newString('Castano')
newString('Castro')
newString('Castro Brothers')
newString('Catelli')
newString('Cavana')
newString('C&amp;C')
newString('C.C.I. Royal Satin Selection')
newString('C. E. Beck')
newString('Cedar Joe')
newString('Cedros')
newString('Celestino Vega')
newString('Celestino Vega (DR)')
newString('Celestino Vega (Indonesia)')
newString('Central Cigars')
newString('C.E.O.')
newString('Cerdan')
newString('Cesar Cigar Factory')
newString('C&#39;est La Vie')
newString('cez')
newString('Cezar Bronner')
newString('CF Dominicana')
newString('CFO')
newString('C.Gars Ltd')
newString('Chaba')
newString('Chacaro Black Stallion')
newString('Chairman&#39;s Choice')
newString('Chamuco')
newString('Charatan')
newString('Charles Denby')
newString('Charles Fairmorn')
newString('Charles Parker')
newString('Charles the Great (Finck)')
newString('Chateau Amaretto')
newString('Chateau Real By Drew Estate')
newString('Chatily&#39;s')
newString('Chavelo')
newString('Chaveta')
newString('Chavon (Thompson)')
newString('Cheap Bastard')
newString('Cheap Humidors')
newString('Chess')
newString('Chessman Royal Reserve')
newString('Cheval')
newString('Chevere')
newString('Chevere by Villiger Ireland')
newString('Cheyenne')
newString('Chicamocha')
newString('Chico')
newString('Chieftain&#39;s')
newString('Chimera')
newString('Chinchalero (formerly Cucaracha, El Cubanito)')
newString('Chinnock Cellars')
newString('Chisum')
newString('Christian of Denmark')
newString('Christo 1886')
newString('Chubbys (Cuban Stock)')
newString('Chub Cigar')
newString('Cibao')
newString('Ciboney')
newString('Cicero')
newString('Cielo')
newString('Cienfuegos (DR)')
newString('Cienfuegos (Reyes)')
newString('Cifuentes')
newString('Cifuentes (Cuban)')
newString('Cigar5packs.com')
newString('Cigar Bodega')
newString('Cigar.com')
newString('Cigar Compadres')
newString('Cigar Express')
newString('Cigar Factory - New Orleans')
newString('Cigar Factory Outlet')
newString('Cigar Family')
newString('Cigar Federation')
newString('Cigar Hut')
newString('Cigar King')
newString('Cigar of the Gods')
newString('Cigar One')
newString('Cigar Pequeno')
newString('Cigar Place')
newString('Cigar Pride')
newString('Cigars Direct')
newString('Cigars ETC')
newString('Cigars International')
newString('Cigars in the Keys')
newString('Cigars of Habanos')
newString('Cigars Rolled by Cubans')
newString('Cigar Station')
newString('Cigar (The Cigar)')
newString('Cinchalero')
newString('Cinco Estrellas')
newString('Cinta Azul')
newString('Cipriano')
newString('Cirilo')
newString('Cisso')
newString('Claddagh Reserva')
newString('Clasico')
newString('Classic')
newString('Classico de Continental')
newString('CLE')
newString('Clementine')
newString('Clipper')
newString('Clipper Gold Reserve')
newString('Club Classis')
newString('Club Havana (by Cubanissimo)')
newString('Clubmaster')
newString('Club Sweets')
newString('Cocinero')
newString('Cocoa')
newString('Cohiba')
newString('Cohiba (Cuban)')
newString('Cohiba (Monticristi Company)')
newString('Cojimar')
newString('Colba 1492')
newString('Colinas')
newString('Colita')
newString('Col\xc3\xb3n')
newString('Columbus (Honduras)')
newString('Columbus (Thompson)')
newString('Commandante')
newString('Commodore')
newString('Companion')
newString('Compay (by Perdomo)')
newString('Competere')
newString('Conchita de Zarate')
newString('Conch Republic')
newString('Condal')
newString('Condega (Nicaragua Cigar Co.)')
newString('Condega (Tabacalera Tropical)')
newString('Conestoga')
newString('Conga Caliente')
newString('Connecticut Crazy')
newString('Connoisseur Choice: Dominican')
newString('Conquista (by Rocky Patel)')
newString('Conquistador (Mexico)')
newString('Conquistador (Nicaragua)')
newString('Constantin')
newString('Constellation')
newString('Consuegra')
newString('Conuco')
newString('Conucos')
newString('Cool Cat')
newString('Copacabana')
newString('Copa Del Sol (Alec Bradly)')
newString('Copa Havana')
newString('Copa Havana Reserve Speciale du Cameroun')
newString('Copanecos')
newString('Coppo')
newString('Coral Reef')
newString('Corazon (Davidoff)')
newString('Cordoba &amp; Morales')
newString('Cordova')
newString('Core Zero (CZ Cigars)')
newString('Cornerstone')
newString('Coroa Real')
newString('Corola')
newString('Corona Cigar')
newString('Corps Diplomatique')
newString('Correvon')
newString('Cortez')
newString('Cortez Cigars')
newString('Cortina')
newString('Cosechero (Thompson)')
newString('Cosmo')
newString('Costa')
newString('Costa Brava')
newString('Costa Dorada')
newString('Costa Verde')
newString('Cost Cutter (Corona Cigar Co.)')
newString('Coticas')
newString('Cotui')
newString('Courvoiser')
newString('Craftman&#39;s Bench')
newString('Crate')
newString('Credo')
newString('Creme de Jamaica')
newString('Creme de Jamaica (Jamaica)')
newString('Cremo')
newString('Cremosa Cubana')
newString('Creole Cigar Factory')
newString('Crimson Lord')
newString('Crispin Pati\xc3\xb1o')
newString('Cristal de Venezuela')
newString('Cristo Cubanos')
newString('Crossfire')
newString('Crown Classic')
newString('Crown Fumas')
newString('Crown Jewel (M. Misti)')
newString('Crown Vintage')
newString('Crown White Label')
newString('Crux')
newString('Cruz Real')
newString('CSB')
newString('CSX')
newString('Cuaba')
newString('Cu-Avana')
newString('Cuba Aliados')
newString('Cuba Caiman')
newString('Cubadom')
newString('Cuba Libre')
newString('Cubanacan (by Tarazona cigars)')
newString('Cubana Fina')
newString('Cubana (House of Horvath)')
newString('Cubana Real Semilla (by Esteban Carreras)')
newString('Cuban Aristocrat')
newString('Cubana Royale')
newString('Cubana Select (Nick&#39;s Cigar World)')
newString('Cuban Blend (Best Cigar Prices)')
newString('Cuban Bullet (by Perdomo)')
newString('Cuban Cigar Company')
newString('Cuban Cigar Factory')
newString('Cuban Cigars 2U')
newString('Cuban Classics')
newString('Cuban Coffee (Mike&#39;s Cigars)')
newString('Cuban Crafters')
newString('Cuban Delights')
newString('Cuban Desire')
newString('Cuban Diplomat')
newString('Cuban Exile')
newString('Cuban Heirloom')
newString('Cuban Heirloom Sun grown')
newString('Cuban Honeys')
newString('Cubanidad')
newString('Cubanissimo')
newString('Cuban Leaf')
newString('Cubano Claro')
newString('Cubano Especiales')
newString('Cubanos')
newString('Cuban Paradise')
newString('Cuban Parejo')
newString('Cuban Pleasures')
newString('Cuban Rejects (Ventura Cigar)')
newString('Cuban Rounds')
newString('Cuban Sandwich')
newString('Cuban Segundos')
newString('Cuban Selection (by Kristoff)')
newString('Cuban Stock')
newString('Cuban Style (Nat Cicco)')
newString('Cuban Throwouts')
newString('Cuban Twist')
newString('Cubao (Philippines)')
newString('Cuba Rica Tabacalera')
newString('Cuba&#39;s Famous Brands')
newString('Cubatabaco')
newString('Cubella')
newString('Cubero')
newString('Cubita')
newString('Cuenca')
newString('Cuesta Rey')
newString('Cueto')
newString('Cueto (Cuban)')
newString('Cuevas')
newString('Cuevas Habanos')
newString('Cugine')
newString('Cult')
newString('Culture')
newString('Cumbres de Puriscal')
newString('Cumpay (Maya Selva Cigars)')
newString('Cupey')
newString('Cupido')
newString('Curivari')
newString('Cusano')
newString('Custom Tobacco')
newString('Cutter&#39;s Cigar Emporium')
newString('Cuvee')
newString('C&amp;V')
newString('CVM Cigars')
newString('CyB (formerly Cuenca y Blanco)')
newString('Cyrilla')
newString('Dabos')
newString('DaGars')
newString('Dale Earnhardt Jr.')
newString('Damn Good (Best Cigar Prices.com)')
newString('Damn Good Dominicans')
newString('Daniel Marshall')
newString('Danli Reserve')
newString('Danlys')
newString('Dannemann')
newString('Danson Clasico')
newString('Dante')
newString('Dark Shark')
newString('Davidoff')
newString('Davidoff (Cuban)')
newString('Davies')
newString('Da Vinci')
newString('DAWA')
newString('DCO')
newString('D&#39;Crossier')
newString('Dea')
newString('Deadwood Tobacco Company')
newString('Dean&#39;s')
newString('Debonaire')
newString('Decision')
newString('Deco Drive')
newString('De Cossio')
newString('De Diego')
newString('Defiance')
newString('Defiant')
newString('De Grisogono')
newString('De Huifkar')
newString('De Kayang')
newString('De La Concha')
newString('Del Campo')
newString('Delectados')
newString('De Leon')
newString('De Leon Cigars')
newString('Delicados (Augusto Reyes)')
newString('Deliciosos (Cuban Stock)')
newString('Del Paraiso')
newString('Deluxe')
newString('Del Valle')
newString('Denobili')
newString('De Nobili')
newString('De Olifant')
newString('Deseo')
newString('Deseo Sombrio')
newString('DeSiena')
newString('Devil&#39;s Weed')
newString('D&#39;Fernandino')
newString('Diablo')
newString('Diamante')
newString('Diamond Crown')
newString('Diana Silvius')
newString('Diego de Ocampo (Thompson)')
newString('Diego Silang')
newString('Diesel')
newString('Diesel (by Rocky Patel)')
newString('Di Fazio')
newString('Diferente')
newString('Dignity')
newString('Dimeola')
newString('Diogenes Puentes')
newString('Diplomaticos')
newString('Discover 1492')
newString('Dissident')
newString('Djarum')
newString('Doc Holliday')
newString('Dog Walker')
newString('Dolce Amaretto')
newString('Dolce Vita')
newString('Domaine de Lavalette')
newString('Domenico')
newString('Domenico (Greece)')
newString('Domeza')
newString('Domingold')
newString('Dominican 3rds')
newString('Dominicana Superba')
newString('Dominican Blanco (Best Cigar Prices)')
newString('Dominican Bundles (Antillian Cigar Corp)')
newString('Dominican Delicias')
newString('Dominican Elites')
newString('Dominican Especiale')
newString('Dominican Estates')
newString('Dominican Green Label')
newString('Dominican Nude Bundles (Best Cigar Prices)')
newString('Dominicano')
newString('Dominican Original (Mike&#39;s Cigars)')
newString('Dominican Overruns (Holts)')
newString('Dominican Prime Select')
newString('Dominican Rejects')
newString('Dominican Republic Gold')
newString('Dominican Royale')
newString('Dominican Santiago Selection')
newString('Dominican Short Run (DSL)')
newString('Dominican Specials')
newString('Dominican Special Selection')
newString('Dominican Supreme')
newString('Dominique')
newString('Domino Park')
newString('Dom Quixote')
newString('Don Abram Harris')
newString('Dona Elba')
newString('Dona Ero')
newString('Dona Flor')
newString('Dona Ines')
newString('Don Alberto')
newString('Don Alfredo')
newString('Don Alfredo (Cuban)')
newString('Dona Lydia')
newString('Don Antonio')
newString('Don Antonio (Germany)')
newString('Don Antonio Pellegrino')
newString('Dona Patricia')
newString('Don Armando')
newString('Don Asa')
newString('Don Aurelios')
newString('Don Barco')
newString('Don Barreto')
newString('Don Benigno')
newString('Don Bernardo')
newString('Don Bienve')
newString('Don Brotto')
newString('Don C\xc3\xa1ndido')
newString('Don Capitano')
newString('Don Carbone')
newString('Don Casimiro Collection')
newString('Don Cassieni')
newString('Don Cesar')
newString('Don Chango')
newString('Don Chicho')
newString('Don Chuchu (Thompson)')
newString('Don Cicero')
newString('Don Cirilo')
newString('Don Collins')
newString('Don Conti')
newString('Don Corazza')
newString('Don Corleone')
newString('Don Diego')
newString('Don Douglas')
newString('Don Duarte')
newString('Don Elias')
newString('Don Elio&#39;s')
newString('Don Elliot')
newString('Don Ernesto')
newString('Don Escobar')
newString('Don Fano (Thompson)')
newString('Don Fausto')
newString('Don Felo')
newString('Don Fernando')
newString('Don Fife')
newString('Don Fonso')
newString('Don Francisco')
newString('Don Gabriel')
newString('Don Garcia')
newString('Don Geronimo')
newString('Don Gonzales')
newString('Don Gonzalez')
newString('Don Goyo')
newString('Don Guillermo')
newString('Don Horacio del Monte')
newString('Don Jacinto')
newString('Don James Sincero')
newString('Don Jesus')
newString('Don Jose')
newString('Don Jose Correa')
newString('Don Juan (Costa Rica)')
newString('Don Juan (Dominican)')
newString('Don Juan (Guatemala)')
newString('Don Juan (Nic)')
newString('Don Juan Urquijo')
newString('Don Julian')
newString('Don Julio')
newString('Don Kike')
newString('Don Kiki')
newString('Don Lachos')
newString('Don Lencho')
newString('Don Leo')
newString('Don Leon')
newString('Don Leoncio')
newString('Don Lino')
newString('Don Longo')
newString('Don Lucas')
newString('Don Lugo (Thompson)')
newString('Don L. &amp; Ventura')
newString('Don Macho')
newString('Don Manolo')
newString('Don Manuel')
newString('Don Marcos')
newString('Don Mariano')
newString('Don Mateo')
newString('Don Melo')
newString('Don Miguel')
newString('Don Nicolas')
newString('Don Nino')
newString('Don Nobody (Corona Cigar Co.)')
newString('Don Norberto')
newString('Don Oscar&#39;s')
newString('Don Osvaldo')
newString('Don Otilio')
newString('Don Pablo')
newString('Don Pacheco')
newString('Don Pancho')
newString('Don Pedro')
newString('Don Pedro Ramos')
newString('Don Pepe')
newString('Don Pepin Garcia (My Father Cigars)')
newString('Don Porfirio')
newString('Don Priamo')
newString('Don Purito (by Cubanissimo)')
newString('Don Quijote')
newString('Don Quixote')
newString('Don Rafael')
newString('Don Ramon')
newString('Don Ramos')
newString('Don Rene')
newString('Don Rene de Cuba')
newString('Don Rex')
newString('Don Rey')
newString('Don Rigo')
newString('Don Rios')
newString('Don Rivera')
newString('Don Rogue')
newString('Don Ronaldo')
newString('Don Rosa')
newString('Don Rubio')
newString('Don Sebastian')
newString('Don Sergio Ramar')
newString('Don Seville (Hon)')
newString('Don Seville (Nic)')
newString('Don Smith')
newString('Don Tito')
newString('Don Tomas')
newString('Don Tuto')
newString('Don Ursulo')
newString('Don Vicente')
newString('Don Yayo')
newString('Don Yeyo')
newString('Don Zamora')
newString('Dos Amigos')
newString('Dos Hermanos Royal Collection')
newString('Dos Hombres')
newString('Dos Reinas')
newString('Dos Rios')
newString('Doublegun')
newString('Double Happiness')
newString('Doubloons')
newString('D.P. Cigars (Digna Polanco)')
newString('DRAM (C&amp;C cigars)')
newString('Dreams')
newString('Drew Estate')
newString('Dr. Funk')
newString('Dry Slitz')
newString('Duarte 1884')
newString('Duck Commander (Ted&#39;s Cigars)')
newString('Due Mundi')
newString('Dulce Maria')
newString('Dumante')
newString('Dunhill')
newString('Duque')
newString('Durango')
newString('Dutch Delites')
newString('Dutch Masters')
newString('Dutch Treats')
newString('DWT')
newString('Dynamite (by Cubanissimo)')
newString('Dynamite (Indian Head Cigars)')
newString('East Coast Rollers')
newString('East End Cigar Co.')
newString('Eastern Standard (Caldwell Cigars)')
newString('East India Trading Company (K. Hansotia)')
newString('E (by BOTL, LLC (Esencia))')
newString('Eden')
newString('Edgar')
newString('Edmundo Dantes')
newString('Ego')
newString('EH Cigars (Edgar Hoill)')
newString('EIROA (Salud, Amor y Pesetas)')
newString('Ejecutivos')
newString('El Artista (Thompson)')
newString('El Balserito')
newString('El Baton')
newString('El Beso')
newString('El Bigote')
newString('El Botin Dominicano')
newString('El Camino Dominicano')
newString('El Canelo')
newString('El Cantillito')
newString('El Capitan')
newString('El Caudillo')
newString('El Cauto Rojo')
newString('El Cedro')
newString('El Che')
newString('El Cobre (by Oliva)')
newString('El Coloso')
newString('El Coloso (Cuban)')
newString('El Compa')
newString('El Competidor')
newString('El Cortesano')
newString('El Corto Gordo')
newString('El Coto')
newString('El Credito')
newString('El Cubano')
newString('El Cuje')
newString('El Cu\xc3\xb1o')
newString('El Diablo')
newString('El Diamante')
newString('El Dorado')
newString('El Duque')
newString('Elegante')
newString('Elegante&#39;')
newString('El Embargo Cigar Factory')
newString('El Emperador')
newString('Elevation')
newString('El Faro')
newString('El Faro (Thompson)')
newString('El Fenicio')
newString('El Fidel')
newString('El Galan')
newString('El Gaucho')
newString('El Gladiator')
newString('El Gordo')
newString('El Grande Miguel')
newString('El Gran Rey')
newString('El Guajiro')
newString('El Hippie')
newString('El Incomparable (Texas Cigar Brothers)')
newString('El Jefe (Cigars Cartel of America)')
newString('El Kajibo')
newString('El Laguito')
newString('El Macco')
newString('El Mejor')
newString('El Mundo del Tabaco')
newString('Elogio')
newString('El Original')
newString('El Paraiso')
newString('El Primer Mundo')
newString('El Producto')
newString('El Reloj')
newString('El Rey de Florez')
newString('El Rey del Mundo')
newString('El Rey del Mundo (Cuban)')
newString('El Rey de Prussia')
newString('El Rico Habano')
newString('El Sabinar')
newString('El Sabor de Miami')
newString('El Sarare')
newString('El Senor (Binnys)')
newString('El Serio')
newString('El Sol')
newString('El Sublimado (Texas Cigar Brothers)')
newString('El Suelo')
newString('El Sueno')
newString('El Taino Cedar')
newString('El Tiante')
newString('El Titan de Bronze')
newString('El Trelles')
newString('El Triunfador (by Tatuaje)')
newString('El Triunfo')
newString('El Trofeo Habano')
newString('El Unicorno')
newString('El Verso')
newString('Embassy')
newString('Emerson')
newString('Emersonscigars.com')
newString('Emigrante')
newString('Emilio')
newString('Emilio Reyes')
newString('Emperor')
newString('Empress of Cuba')
newString('Enanos')
newString('Encanto')
newString('Encore')
newString('En el Punto')
newString('ENKI')
newString('Entourage')
newString('Entrepreneur')
newString('E.P. Carrillo')
newString('Epic')
newString('Epicurean Cigars')
newString('Epoca (Nat Sherman)')
newString('Equilibrium')
newString('Equus')
newString('Erez')
newString('Eric Mellgren')
newString('Erik')
newString('Erte')
newString('Escarabin')
newString('Escudo Cubano')
newString('Esencia')
newString('Espada de Oro')
newString('Espanola')
newString('Especiales')
newString('Esperanza')
newString('Espinosa')
newString('Espinosa y Ortega (EO brands)')
newString('Esplendido')
newString('ESQ')
newString('Esse')
newString('Est. 1844')
newString('Estavan')
newString('Estavan Cruz')
newString('Esteban Carrera')
newString('Esteban Carreras')
newString('Esteliano')
newString('Esteli Overruns')
newString('Esteli Ruiz')
newString('Estrella')
newString('Estrella Blanca')
newString('Eterno (by Perdomo)')
newString('Ether')
newString('Etiqueta Azul')
newString('Eureka')
newString('Evelio')
newString('Evel Knievel Signature Series')
newString('Evermore')
newString('Everyday Joe')
newString('Evil Clown')
newString('Evil Genius Cigars')
newString('Evita')
newString('Exactus')
newString('Excalibur (European)')
newString('Excelsior')
newString('Exclusive Cigars')
newString('Exhibit')
newString('Exile')
newString('Express Imports')
newString('Exquisito (Cuban Stock)')
newString('E. Zarzuela')
newString('Ezra Zion')
newString('Factory Fresh')
newString('Factory Outlet')
newString('Factory Straight')
newString('Factory Throwouts')
newString('Fair Exchange')
newString('FAKE Cohiba - Mexican Variety')
newString('Fake Cuban Cohiba')
newString('Fallen Angel')
newString('Falsetto')
newString('Falto')
newString('Famous')
newString('Fanning`s')
newString('Farias')
newString('Farmer&#39;s Select')
newString('Farnam Drive')
newString('Fatboy')
newString('Father &amp; Son Cigars')
newString('Faux King Gold Label')
newString('Faxas')
newString('F. D. Grave')
newString('Fedelis')
newString('Felipe Forza')
newString('Felipe Gregorio')
newString('Felix Assouline Cigars')
newString('Felungo')
newString('Fernandez')
newString('Fernando Leon (by La Aurora)')
newString('FG 2009')
newString('Fidalgro Negro')
newString('Fidelis')
newString('Fidel&#39;s')
newString('Fields of Gold')
newString('Fiero')
newString('Fifth Centennial')
newString('Fighting Cock (Nicaragua)')
newString('Fighting Cock (Philippines)')
newString('Figurado Reserve')
newString('Figurados')
newString('Filipinas')
newString('Finck')
newString('Fine Catch')
newString('Finest Cuban Cigars')
newString('Finnegan&#39;s Reserve')
newString('Fire (by Indian Tabac)')
newString('First Lady of the World')
newString('First Priming')
newString('Fittipaldi')
newString('Five Star')
newString('Flamenco')
newString('Flatbed Cigar Co.')
newString('Fletcher Cigar Company')
newString('Fleur de la Reine')
newString('Floras')
newString('Flor Cubana')
newString('Flor de A. Allones')
newString('Flor de Amor')
newString('Flor de Baloney')
newString('Flor de Besana')
newString('Flor de Camaguey')
newString('Flor de Carbonell')
newString('Flor de Cesar')
newString('Flor de Cielo')
newString('Flor de Consuegra')
newString('Flor de Copan')
newString('Flor de Dios')
newString('Flor de Dominguez')
newString('Flor de Farach')
newString('Flor de Filipinas')
newString('Flor de Florez')
newString('Flor de Gonzalez')
newString('Flor de honduras')
newString('Flor de Jalapa')
newString('Flor de Jardin (Texas Cigar Brothers)')
newString('Flor de Java')
newString('Flor de Jose')
newString('Flor del Aire')
newString('Flor de la Isabela')
newString('Flor del Caribe')
newString('Flor de Lis (Thompson)')
newString('Flor de los Reyes')
newString('Flor del Punto')
newString('Flor del Todo')
newString('Flor de Manila')
newString('Flor de Matacapan')
newString('Flor de Mexico')
newString('Flor de Murias')
newString('Flor de Nicaragua')
newString('Flor de Oliva')
newString('Flor de Oro')
newString('Flor de Selva (Maya Selva)')
newString('Flor De Valle (Warped cigars)')
newString('Flor de Ybor City')
newString('Florentino')
newString('Flores y Rodriguez (by PDR)')
newString('Flor Fina')
newString('Florida Queen')
newString('Flor Isla Habana')
newString('Flor Real')
newString('Flower City Special Reserve')
newString('Fogo')
newString('Fonseca')
newString('Fonseca (Cuban)')
newString('Forcade &amp; Son')
newString('For de los Reyes')
newString('Fortuna de Honduras (Finck)')
newString('Fortunado (Thompson)')
newString('Fortunato')
newString('Forty Creek')
newString('Foundry')
newString('Four Kicks (Crowned Heads)')
newString('Foyle')
newString('FP')
newString('Francisco de Miranda')
newString('Francisco Hernandez')
newString('Francisco Pla')
newString('Franco')
newString('Frankenmuth Original Cigar Company')
newString('Frank Herrera')
newString('Frank Llaneza 1961')
newString('Frank Vincent')
newString('Fratello')
newString('Free Cuba')
newString('Fresh Rolled')
newString('Fuego de Dios')
newString('Fuego de la Noche')
newString('Fuego del Rey')
newString('Fuente Fuente OpusX')
newString('Fuentes Crucet')
newString('Fuma Dominica Especial')
newString('Fumadores')
newString('FUMARE')
newString('Fuma Suprema')
newString('Fundacion Ancestral')
newString('Fundadores Jamaica')
newString('F\xc3\xbcrst Bismarck')
newString('Fusion')
newString('G2')
newString('Gabriela')
newString('Galactico')
newString('Galiano')
newString('Gallardo')
newString('Gambler')
newString('Game Day')
newString('G.A.R. by George Rico')
newString('Garcia y Vega')
newString('Garo')
newString('Garofalo')
newString('Gate City Cigars')
newString('Gato')
newString('Gaucho')
newString('GB Naked')
newString('G. De Graaff')
newString('GDW (Guillen Cigars)')
newString('Geminis')
newString('General Grant')
newString('General Honduran')
newString('Genuine')
newString('Genuine Counterfeit')
newString('George Rico S.T.K.')
newString('Georges Reserve')
newString('Gerant&#39;s')
newString('G\xc3\xa9rard P\xc3\xa8re et Fils')
newString('Geronimo')
newString('Giaconda')
newString('Gibraltar (Caldwell Cigars)')
newString('Gilbert de Montsalvat')
newString('Gilberto Cubana')
newString('Gilberto Oliva')
newString('Gil Gonzales Davila')
newString('Gioconda')
newString('Gispert')
newString('Gispert (Cuban)')
newString('Gloria de La Romana')
newString('Gloria de Leon (Curivari)')
newString('Gloria Palmera')
newString('God of Fire')
newString('Golden Class (Felipe Gregorio)')
newString('Golden Harvest')
newString('Golden Sun')
newString('Gold Rush')
newString('Gold Strike (by Royal Gold)')
newString('Golfers&#39; Choice')
newString('Gonzalez Habano Co.')
newString('Good Times')
newString('Gordos')
newString('Gorilla Fingers')
newString('Gourmet Dessert')
newString('Governor&#39;s')
newString('Goya')
newString('Grabs')
newString('Gramercy')
newString('Gran Alfonso Cigars')
newString('Gran Cantidad')
newString('Gran Cuba')
newString('Grand Cameroon')
newString('Grande')
newString('Grandes de Espa\xc3\xb1a')
newString('Grand Havana')
newString('Grand Maduro')
newString('Grand Marnier')
newString('Grand Nica')
newString('Grand Virrey')
newString('Gran Habano')
newString('Gran Havana')
newString('Gran Momba')
newString('Gran Vida by Rocky Patel')
newString('Gran Virrey')
newString('Grass')
newString('Graycliff')
newString('Great (bleeping) Cigars')
newString('Great Lakes Cigar Company')
newString('Great Wall')
newString('Greenville Avenue Tobacco Co.')
newString('Gridiron')
newString('Griffin&#39;s')
newString('GR Specials')
newString('GTO Cigars')
newString('Guajiro')
newString('Guama')
newString('Guantanamera')
newString('Guantanamera (Cuban)')
newString('Guaranteed Jamaica')
newString('Guayacan')
newString('Guerra')
newString('Guglielmo Winery')
newString('Guillermo Leon (by La Aurora)')
newString('Guillermo Pena')
newString('Gunslinger (Outlaw Cigars)')
newString('Gurkha')
newString('Guzman')
newString('G&amp;V Game')
newString('GWAR (by Tatuaje)')
newString('Habana Cuba (Oliveros)')
newString('Habana Delight')
newString('Habana Gold')
newString('Habana Leon')
newString('Habana Port')
newString('Habana Real')
newString('Habana Real (US)')
newString('Habana Real (USA)')
newString('Habana Treasure')
newString('Habanera')
newString('Habanera 78')
newString('Habanero 87')
newString('Habaneros')
newString('Habanica')
newString('Habanique')
newString('Habano')
newString('Habano Clasico')
newString('Habano Primero')
newString('Habanos')
newString('Habanos (Cuban)')
newString('Habanos del Eden')
newString('Habanos Esplendidos')
newString('Habanos Puros')
newString('Hacienda Rio')
newString('Hajenius')
newString('H. A. Ladrillos')
newString('Hamiltons')
newString('Hammer &amp; Sickle')
newString('Hampton Arms')
newString('Handelsgold')
newString('Happy Hour')
newString('Harly')
newString('Harrows')
newString('Harvill')
newString('Hasa Rey')
newString('Hat&#39;s Off')
newString('Hatuey')
newString('Hauptmann&#39;s')
newString('Havache')
newString('Hav-a-Joe (Discontinued)')
newString('Havana')
newString('Havana Blend (Finck)')
newString('Havana Cigar')
newString('Havana Cigar Company')
newString('Havana Cigars-Don Pedro Ramos')
newString('Havana Classico')
newString('Havana Cloud')
newString('Havana Cognac')
newString('Havana Cool')
newString('Havana Cream')
newString('Havana Dreams')
newString('Havana Especial')
newString('Havana Honeys')
newString('Havana House')
newString('Havana Humidor')
newString('Havana Jim')
newString('Havana Night Club')
newString('Havana Originals')
newString('Havana Preferred (JM Tobacco Inc.)')
newString('Havana Republic')
newString('Havana Rum')
newString('Havana Soul')
newString('Havana Star')
newString('Havana Sun Grown')
newString('Havana Sunrise')
newString('Havana Sweets')
newString('Havana Tobaccos')
newString('Havana Verde')
newString('Hav-A-Tampa Jewel')
newString('Hawk')
newString('HE')
newString('Headley Grange (by Crowned Heads)')
newString('Heavenly')
newString('Hecha Humo')
newString('Hecho a Mano Dominicana')
newString('Hecho Con Corazon (Crowned Heads)')
newString('Helix')
newString('Hendrik Kelner')
newString('Henri Poupart')
newString('Henri Wintermans')
newString('Henry Clay')
newString('Henry George')
newString('Herederos')
newString('Herederos De Robaina')
newString('Herfdog')
newString('Hermosa Cigars')
newString('Herrera Esteli (by Drew Estate)')
newString('Hesitant Pirate')
newString('Hickey Bros.')
newString('Hidalgo')
newString('Highlander')
newString('High Monk')
newString('Hight')
newString('Hill Country Humidor')
newString('Hirschsprung')
newString('Hirsh &amp; Garcia')
newString('Hispaniola')
newString('His Royal Majesty')
newString('H M (Humberto Mendoza)')
newString('Hobo')
newString('Hoboken Premium')
newString('Hobson&#39;s Choice')
newString('Hoffman House')
newString('Hofnar')
newString('Hoja Copan')
newString('Hoja Cubana')
newString('Hoja de Flores')
newString('Hoja de Mexicali')
newString('Hoja de Nicaragua')
newString('Hoja de Oro')
newString('Hoja Real')
newString('Holt&#39;s')
newString('Holy Smokes Cigars')
newString('Hombre de Oro')
newString('Hommage 1492')
newString('Honduran Cuban Tobaccos')
newString('Honduran Estates')
newString('Honduran Factory Corojos (JR Cigars)')
newString('Honduran Gold')
newString('Honduran Habano')
newString('Honduran Overruns')
newString('Honduras Caribbean')
newString('Honduras Special')
newString('Honey Honey')
newString('Hookah')
newString('Hopz (Ted&#39;s Cigars)')
newString('Horsepower')
newString('Hot Ash')
newString('House of Cigars')
newString('House of Dublin')
newString('House of Gaspar')
newString('House Resolution')
newString('Hoya de Habano')
newString('Hoyo 19')
newString('Hoyo de Casa')
newString('Hoyo de Honduras')
newString('Hoyo de Monterrey')
newString('Hoyo de Monterrey (Cuban)')
newString('HSR, Honduran Short Run (by Camacho)')
newString('Hugo Cassar')
newString('Hula Girls')
newString('Humo Jaguar')
newString('Humo Santo')
newString('H. Upmann')
newString('H. Upmann (Cuban)')
newString('HuzGar')
newString('HVC (by Casa Fernandez)')
newString('i80')
newString('Ibold')
newString('Iconic Leaf Cigar Company')
newString('Iguana (Thompson)')
newString('Illuminati')
newString('Illusione')
newString('Illustrious Goodfellas')
newString('Imperial Stout (by Gran Habano)')
newString('Imperio Cubano')
newString('Inception')
newString('Independencia (DR)')
newString('Indian')
newString('Indiana Slims')
newString('Indian Cha Cha Cha')
newString('Indian Dominican')
newString('Indian Fire')
newString('Indian Head')
newString('Indian Princess')
newString('Indian Tabac')
newString('Indigo')
newString('Industrial Press')
newString('Inferno (by Oliva)')
newString('Infiesta')
newString('Infiniti')
newString('Inka Secret Blend (C.Gars Ltd.)')
newString('Inmenso')
newString('International')
newString('International Cigar Factory Outlet')
newString('ION')
newString('Iracema')
newString('Iron Horse')
newString('Isabela')
newString('Isabella')
newString('Isla de Cuba')
newString('Island')
newString('Island Amaretto')
newString('Island Blendz')
newString('Island Cigar Factory')
newString('Island Delights')
newString('Islands')
newString('Isla Rica')
newString('Isle\xc3\xb1os')
newString('ISOM')
newString('Isthmus')
newString('Iwan Ries &amp; Co.')
newString('JAD')
newString('Jade Cheroots')
newString('Jaguar of Belize')
newString('Jaime Garcia')
newString('Jalopy')
newString('Jamaica Bay')
newString('Jamaica Heritage')
newString('Jamaican Vanilla')
newString('James Norman')
newString('Jameson')
newString('Jamiaca Legacy')
newString('Jane')
newString('Java (by Drew Estate)')
newString('Javier Vizcaino')
newString('Jaxsin')
newString('JB Selection')
newString('J. Castanon')
newString('J. Cortes')
newString('JC The Cuban Roller')
newString('J&amp;D')
newString('JD Cigars')
newString('J.D. Howard (Crowned Heads)')
newString('Jenuwine')
newString('Jericho (by Camacho)')
newString('Jericho Hill (Crowned Heads)')
newString('Jersey Joe&#39;s')
newString('JFC (Just for Catalogs)')
newString('JFC Tobacco')
newString('JFR (Just for Retailers)')
newString('JF (Sri Lanka)')
newString('J. Fuego')
newString('J. Grotto (Ocean State Cigars)')
newString('J.Grotto (Ocean State Cigars)')
newString('Jibaro')
newString('Jimenez')
newString('Jimmy Lakey&#39;s Cigar Company')
newString('J.L. Salazar y Hermanos')
newString('JML 1902')
newString('JM&#39;s')
newString('Joe&#39;s Reserve')
newString('John Aylesbury')
newString('John Bull')
newString('John Hay')
newString('John Starks (Dominican Legend Cigars)')
newString('John T&#39;s')
newString('Jordan Alexander III')
newString('Jose Bartolo (Egypt)')
newString('Jose Benito')
newString('Jose Carlos')
newString('Jose del Valle')
newString('Jose Diamante')
newString('Jose Dominguez (DR)')
newString('Jose Dominguez (Palma)')
newString('Josefina')
newString('Jos\xc3\xa9 Girb\xc3\xa9s')
newString('Jose Llopis')
newString('Jose L. Piedra')
newString('Jose Marti')
newString('Jose M. Losa (by La Tradicion Cubaba)')
newString('Jose Paco')
newString('Jose Ramon Villar')
newString('Jose Seijas')
newString('Journeys')
newString('Joya Cubana')
newString('Joya de Canarias')
newString('Joya de Havana')
newString('Joya de Honduras')
newString('Joya de la Romana')
newString('Joya del Cibao')
newString('Joya del Jefe')
newString('Joya del Rey')
newString('Joya de Nicaragua')
newString('Joya Real')
newString('Joyas de Panama')
newString('Joyitas')
newString('Jpb')
newString('JR Cigars')
newString('J&amp;R Famous')
newString('J.R. Tobacco')
newString('Juan Clemente')
newString('Juan Guillermo de Robles')
newString('Juan Lopez')
newString('Juan Lopez (Cuban)')
newString('Juan Manuel Torres')
newString('Juan y Ramon')
newString('Jucy Bluntarillo')
newString('Judges Cave')
newString('Julia Marlowe')
newString('Juliany')
newString('Juneda')
newString('Jungle Smokes')
newString('Justus van Maurik')
newString('JW')
newString('Kafie 1901')
newString('Kahlua')
newString('K. A. Kendall')
newString('Kalibur')
newString('Kangaroo Alley')
newString('Kauai')
newString('K-Cigars')
newString('Keep Moving')
newString('Kelner')
newString('Kenners Keus')
newString('Kensington')
newString('Kentucky')
newString('Kentucky Derby (Ted&#39;s Cigars)')
newString('Kentucky Fire Cured MUWAT (by Drew Estate)')
newString('Kentucky Gentlemen')
newString('Kentucky Moonshine')
newString('Kevin Michaels')
newString('Key West Cigar')
newString('Key West Cigars')
newString('K. Hansotia')
newString('Kick Ass Quality Cigars')
newString('King Cobra')
newString('King David')
newString('King Dominican')
newString('King Edward')
newString('King Kong Specials')
newString('Kingpin')
newString('King Richard')
newString('Kings Club')
newString('King&#39;s Court')
newString('Kingston')
newString('Kingstown')
newString('Kings (unlimited)')
newString('Kinky Friedman')
newString('Kinsella Fino')
newString('Kiskeya')
newString('Klafter&#39;s Limited Reserve')
newString('Knockando')
newString('Koala')
newString('Kristian James')
newString('Kristoff')
newString('Kuuts')
newString('La Abeja')
newString('La Aroma de Cuba')
newString('La Aurora')
newString('La Avida')
newString('La Barba')
newString('La Belleza')
newString('La Bestia')
newString('La Boheme')
newString('La Bonita')
newString('La Brisa')
newString('La Campi\xc3\xb1a')
newString('La Caoba')
newString('La Capitana')
newString('La Caridad del Cobre')
newString('La Carolina')
newString('La Casa Grande')
newString('La Casita Criolla (by Tatuaje)')
newString('La Casona')
newString('La Casta')
newString('La Caya')
newString('La Cima')
newString('La Colmena (Warped Cigars)')
newString('La Corona')
newString('La Corona (Cuban)')
newString('La Cosecha')
newString('La Cumanesa')
newString('La Cuna')
newString('La Diferencia Cubana')
newString('La Diligencia')
newString('La Diva')
newString('La Due\xc3\xb1a (Janny Garc\xc3\xada)')
newString('Lady Club')
newString('Lady Jane')
newString('La Eminencia')
newString('La Escepcion')
newString('La Escepcion (Cuban)')
newString('La Esencia del Vino')
newString('La Estrella Cubana')
newString('La Fabuloso')
newString('La Fama')
newString('La Famosa')
newString('La Favorita (Canary Islands)')
newString('La Favorita (Felipe Gregorio)')
newString('La Favorita (Honduras)')
newString('La Fendrich')
newString('La Finca')
newString('La Flor de Armando Mendez')
newString('La Flor de Cano')
newString('La Flor de Cano (Cuban)')
newString('La Flor de Cuba')
newString('La Flor de el Cairo')
newString('La Flor de Java')
newString('La Flor Del Caney')
newString('La Flor Del Caney (Cuban)')
newString('La Flor de los Reyes')
newString('La Flor del Teide')
newString('La Flor de Murias')
newString('La Flor de Navarette')
newString('La Flor de Rafael Gonz\xc3\xa1lez M\xc3\xa1rquez')
newString('La Flor de Ynclan')
newString('La Flor Dominicana')
newString('La Floridita')
newString('La Fontana')
newString('La Francesca')
newString('La Galana')
newString('La Garita')
newString('La Gianna Havana')
newString('La Gloria Cubana')
newString('La Gloria Cubana (Cuban)')
newString('La Gran Fuma')
newString('La Habanera')
newString('La Hara')
newString('La Havanita Cigar Factory')
newString('La Herencia Cubana')
newString('La Herencia de Cuba')
newString('La Hoja Fiesta')
newString('La Hoja Selecta')
newString('La Intimidad')
newString('La Invicta')
newString('La Isla')
newString('La Joya Cubana')
newString('La Joya de San Andres')
newString('La Jugada (Formerly Flor de Esteli)')
newString('La Ley')
newString('La Libertad (DR)')
newString('La Libertad (Nic)')
newString('La Liga')
newString('La Luna')
newString('La Luna de Santa Maria')
newString('La Marinita')
newString('La Maximiliana')
newString('Lamb&#39;s Club (Finck)')
newString('La Meridiana')
newString('La Mezcla Cubana')
newString('La Mia')
newString('La Misi\xc3\xb3n')
newString('La Moneda')
newString('La Native')
newString('La Nubia')
newString('La O&#39;Paree')
newString('La Palina')
newString('La Palma')
newString('La Palma de Oro')
newString('La Paloma (Thompson)')
newString('La Pantera')
newString('La Paz')
newString('La Pefecta')
newString('La Perla Habana')
newString('La Plata')
newString('La Primadora')
newString('La Primera')
newString('La Primorosa')
newString('La Princesa de Cuba')
newString('La Prueba')
newString('Laranja Reserva (Espinosa)')
newString('La Real')
newString('La Regenta')
newString('La Regional')
newString('La Reina')
newString('La Reloba')
newString('La Reserva')
newString('La Restina')
newString('La Ribera')
newString('La Rica')
newString('La Rica Hoya')
newString('La Riqueza')
newString('La Rosa')
newString('La Rosa Especial')
newString('Lars Tetens')
newString('La Sabana (Cuba Tobacco Cigar Co.)')
newString('La Sabana (Nicaraguan)')
newString('La Salle (Thompson)')
newString('La Saola')
newString('Las Cabrillas')
newString('Las Calaveras (Crowned Heads)')
newString('La Selection de Robert')
newString('La Sirena')
newString('Las Memorias Cubanas (by La Tradicion Cubana)')
newString('La Surina')
newString('Las Vegas')
newString('Las Vegas Cigar Co.')
newString('La Tabaqueria')
newString('La Tanita')
newString('L&#39;Atelier')
newString('Latin Gold')
newString('Latin Quarter House of Cigars')
newString('Latitude Zero')
newString('La Tradicion Cubana')
newString('La Tribu')
newString('L&#39;Attitude 18')
newString('La Unica')
newString('Laura Chavin')
newString('Laurato')
newString('La Veleza')
newString('La Vencedora')
newString('La Venga')
newString('La Vida')
newString('La Zona (Espinosa)')
newString('Leaf &amp; Bean')
newString('Le Bonne Cigare')
newString('Leccia Tobacco')
newString('Le Cigar')
newString('LegendArio (by Camacho)')
newString('Legion')
newString('Le Gran Fuma')
newString('Le Hoyo')
newString('Leite &amp; Alves')
newString('Lempira (Nicaragua)')
newString('Lempira Puros (Honduras)')
newString('Leonel')
newString('Leon Jimenes')
newString('Leon (Nicaragua)')
newString('Leon (USA)')
newString('Leopoldo')
newString('Leprechaun')
newString('Leuzzi Fumar')
newString('Lew&#39;s Smokers')
newString('Lex12')
newString('Leyenda')
newString('Lianos Dos Palmas')
newString('Licenciados')
newString('Liga')
newString('Liga (by Drew Estate)')
newString('Liga IV')
newString('Liga Maestro (Mombacho)')
newString('Lion&#39;s Den (Ernesto Padilla)')
newString('Little Big Man')
newString('Little Cigar Factory')
newString('Little Havana')
newString('Little Havana Cigars')
newString('Litto Gomez Diez')
newString('Live')
newString('L. Lynn')
newString('Loaiza uNo')
newString('Lochem')
newString('Lone Wolf')
newString('Longchamp (France)')
newString('Long Island')
newString('Long Live The King (Caldwell Collection)')
newString('Loose Cannon')
newString('Lopez Tonight')
newString('Lord Beaconsfield')
newString('Lord Blackburn')
newString('Lord Clinton')
newString('Los Caleros')
newString('Los Classicos Rejects')
newString('Los Hermanos')
newString('Los Imperialistas')
newString('Los Libertadores')
newString('Los Libertados')
newString('Los Nicas')
newString('Los Nietos Cigars')
newString('Los Patriotas')
newString('Los Perez')
newString('Los Reyes Unidos')
newString('Los Statos')
newString('Lotar')
newString('Lou Rodriguez')
newString('Low Ball Louie&#39;s')
newString('Lucas Santana')
newString('Lucero')
newString('Lucky 8')
newString('Lucky Cigar')
newString('Lucky Dublin')
newString('Luis Alejandro')
newString('Luis Gonzaga')
newString('Luis Martinez')
newString('LUJ')
newString('Luna Azul')
newString('Luna/Laissez-Faire')
newString('Lusitania')
newString('M3')
newString('M.A.C.')
newString('Macabi')
newString('Macanudo')
newString('Macarena')
newString('MacBeth')
newString('Macorix')
newString('Macuro')
newString('Madison')
newString('Madrigal Habana')
newString('Maestro Cubano')
newString('Magellan')
newString('Magicos Cubanos')
newString('Magna Carta')
newString('Magnate')
newString('Magnum Force')
newString('Magus (Armando Ramos)')
newString('Maker&#39;s Choice')
newString('Maker&#39;s Mark (Ted&#39;s Cigars)')
newString('Malaguena')
newString('Mama Rosa')
newString('Mambo Sabroso')
newString('Man')
newString('Mandalay')
newString('Manifiesto')
newString('Manolo&#39;s Factory Overruns')
newString('Man O&#39; War')
newString('Manrique')
newString('Mantequilla')
newString('Manuel Casals')
newString('Marange')
newString('Maravilla')
newString('Marca Fina')
newString('Marco V')
newString('Marcus Daniel')
newString('Mardo')
newString('Maria Divina')
newString('Maria Guerrero')
newString('Maria Mancini')
newString('Mario Palomino')
newString('Mark IV')
newString('Mark Twain')
newString('Marley')
newString('Maroma')
newString('Marques de Gurabo')
newString('Marsh 1840')
newString('Marsh Wheeling')
newString('Martinez')
newString('Martinez/Bazukas')
newString('Mason Dixon Project (Crowned Heads)')
newString('Master Bradley&#39;s Premium Dominican')
newString('Master Roller')
newString('Matacan')
newString('Matador Cigars')
newString('Matilde')
newString('Maximo Gomez')
newString('Maxim&#39;s')
newString('Maxim&#39;s of Paris')
newString('Maxius')
newString('Maxum')
newString('Maya')
newString('Maya Palma')
newString('Mayorga')
newString('MBombay')
newString('M.C.')
newString('McCranies House Brand')
newString('MCW (My Cuban Wheel)')
newString('MD')
newString('MD (Indonesia)')
newString('Meccarillos')
newString('Medal Of Honor')
newString('Mederos')
newString('Mederos Cubanacan')
newString('Medici (by Alec Bradley)')
newString('Medina')
newString('Memoria de Cuba')
newString('Memphis Blue')
newString('Mendez Y Lopez')
newString('Mercedes')
newString('Meros S.A.')
newString('Mexican Emperador')
newString('Mexican Segundos (Luis Martinez)')
newString('Miami Cigar Company')
newString('Miami Mafia (by Cubanissimo)')
newString('Miami Suites')
newString('Mi Barrio')
newString('Michael Lington')
newString('MiCubano')
newString('Middleton')
newString('Middleton Black &amp; Mild')
newString('Miguel Grau')
newString('Miguel Private Cigars')
newString('Miguel y Familia')
newString('MiHabano')
newString('Mi Habano')
newString('Mike Ditka')
newString('Mike&#39;s Cigars')
newString('Milano Cigar Collection')
newString('Milano Santana')
newString('Militia')
newString('Minotaur (by Felipe Gregorio)')
newString('Miraculous Templar')
newString('Miramar')
newString('Miranda')
newString('Miro')
newString('Mister B Handmade')
newString('Mister Hyde&#39;s')
newString('Mi Tierra')
newString('Miura')
newString('Miyares')
newString('M. J. Frias')
newString('MJH')
newString('MOB')
newString('Mocambo')
newString('Mocha')
newString('Mocha Supreme')
newString('Mohican')
newString('Moishe Pipik')
newString('Mombacho')
newString('Mom&#39;s')
newString('Monaco')
newString('Monse\xc3\xb1or de la Habana')
newString('Monse\xc3\xb1or de la Romana')
newString('Montague')
newString('Montalvo')
newString('Montana Sport')
newString('Monte Albar')
newString('Monte Canario')
newString('Monte Carlo (by Camacho)')
newString('Montecristo')
newString('Montecristo (Cuban)')
newString('Montecruz')
newString('Montego')
newString('MontePalma')
newString('Monte Pascoal')
newString('Monte Real')
newString('Monteria')
newString('Montero')
newString('Montes de Oca')
newString('Montes de Oro')
newString('Montesino')
newString('Monte Verde')
newString('Montezuma')
newString('Monument')
newString('Moolah')
newString('Moonshine Crooks')
newString('Moore &amp; Bode')
newString('Morejon y Cuesta')
newString('Moreno Maduro')
newString('Morgan Alexander')
newString('Moroceli')
newString('Morocho')
newString('Morro Castle')
newString('Morton Collection')
newString('Mosaico')
newString('Moscato')
newString('Most Wanted')
newString('Motta')
newString('Moya')
newString('M.P.')
newString('M&amp;R')
newString('Mr. B&#39;s')
newString('Mr Charutos')
newString('Mr. Wonderful')
newString('Mulberry Street Cigar Co.')
newString('Mundi Victor')
newString('Muniemaker')
newString('Murano')
newString('Murcias (Caldwell Cigars)')
newString('Muriel')
newString('Mursuli')
newString('Mya')
newString('My Father')
newString('Mylo&#39;s Castle')
newString('My Own Blend (Paul Olsen)')
newString('Mysterioso')
newString('Mythos')
newString('Mythos (Best Cigar Prices)')
newString('Mythos Solitude')
newString('Nacionales W')
newString('Nadi')
newString('Nafilyan')
newString('Napa')
newString('Napa Reserve')
newString('Nat Cicco')
newString('National Brand')
newString('Nativo')
newString('Nat Sherman')
newString('Naughty Goose')
newString('Navarre')
newString('Navarro')
newString('Navigator')
newString('NEOS')
newString('Neptune')
newString('Nesticos (Plasencia)')
newString('Nestor')
newString('Nestor Miranda')
newString('Nestor Plasencia')
newString('New Cuba')
newString('New Generation')
newString('New Havana Cigars')
newString('New Orleans Cigar Company')
newString('New York')
newString('New York Minute')
newString('Next Generation')
newString('Nica')
newString('Nicahabana')
newString('Nica Libre')
newString('Nicaragua Especial')
newString('Nicaragua Habanos')
newString('Nicaraguan Cream')
newString('Nicaraguan Estates')
newString('Nicaraguan Factory Direct (Tabacalera Tropical)')
newString('Nicaraguan Gold')
newString('Nicaraguan Gordo 2nds (cigar.com)')
newString('Nicaraguan Heirloom')
newString('Nicaraguan Ligero-Laced 2nds (Cigars Int.)')
newString('Nicaraguan Overruns (Holt&#39;s)')
newString('Nicaraguan Special Selection (Casa Fernandez)')
newString('Nicarao')
newString('Nica&#39; Reina')
newString('Nic Biggy')
newString('Nice Guys')
newString('Nick Bada Bing Cigars')
newString('Nicole Miller')
newString('Nikki')
newString('Nimbus (by Felipe Gregorio)')
newString('Nino Vasquez')
newString('Nirvana (Royal Gold)')
newString('Nish Patel')
newString('Nitro')
newString('Nobel')
newString('Nobleza')
newString('Noel Rojas')
newString('Nomad')
newString('Nomi')
newString('Non Plus Ultra')
newString('Novillos (Formerly Stubs by Miura Cigars)')
newString('Nudes')
newString('Nuevitas')
newString('NYC Cigar Co.')
newString('Oakbrook')
newString('Oak Brook Tobacco Company')
newString('Oasis')
newString('Oba! Oba! - by Perdomo')
newString('Obsidian')
newString('Ocaso')
newString('Occidental')
newString('Octavo')
newString('O&#39; Danny Boy')
newString('Oh Que Bueno')
newString('Oja')
newString('Ojeda')
newString('Old Fashioned')
newString('Old Fort Bliss Cigar Company')
newString('Old Havana')
newString('Old Henry')
newString('Old Homestead')
newString('Oldies But Goodies')
newString('Old Port')
newString('Old Powder Keg')
newString('Old School')
newString('Old Virginia')
newString('Olganza')
newString('Oliva')
newString('Oliva (Angel)')
newString('Oliveros')
newString('Olor')
newString('Olor del Cibao')
newString('Olor Nicaragua')
newString('Ol&#39; Times')
newString('Olympia')
newString('Omar Ortez')
newString('Omar Ortiz')
newString('Omega')
newString('One 13')
newString('One-N-Done')
newString('Oneoff')
newString('Onyx')
newString('Optimo')
newString('Orange Label')
newString('Ora Vivo (Armand Assante)')
newString('Orient Express')
newString('Original Cubans')
newString('Origins')
newString('Orinoco 1613')
newString('Ornelas')
newString('Oro Cubano')
newString('Oro de Cuba')
newString('Oro de Esteli')
newString('Oro de Panama')
newString('Oro de Reinitas')
newString('Oro Negro')
newString('Orosi')
newString('Ortega')
newString('Ortez y Turrent')
newString('ORTSAC')
newString('Oscar')
newString('Our Family&#39;s Finest')
newString('Outdoorsman (Camacho)')
newString('Over Production')
newString('Oxford')
newString('Paco')
newString('Padilla')
newString('Padron')
newString('Pai Gow')
newString('Paisanos')
newString('Paket Hemat')
newString('Palma')
newString('Palma Real')
newString('Palmarejo')
newString('Palmas Puro')
newString('Palomino')
newString('Palomitas')
newString('Palo Prieto')
newString('PANA')
newString('Panama Caribbean')
newString('Panama Red')
newString('Pan American')
newString('Pancho Floods')
newString('Pancho&#39;s Reserve')
newString('Panorea')
newString('Panter')
newString('Papayo')
newString('Par')
newString('Paradise Island')
newString('Paradiso Cubano')
newString('Paradiso (San Cristobal)')
newString('Para Siempre')
newString('Paratagas (Cuban)')
newString('Para Ti')
newString('Parcel 77')
newString('Parodi (Avanti)')
newString('Partagas')
newString('Partagas (Cuban)')
newString('Particulares')
newString('Paseana')
newString('Pasha Reserve Collection')
newString('Paso D&#39;Le\xc3\xb3n')
newString('Pastora')
newString('Patoro')
newString('Patriot')
newString('Patriota')
newString('Patron Anejo (Ted&#39;s Cigars)')
newString('Paul Garmirian')
newString('Paul stulac')
newString('Payne-Mason')
newString('P. Bello y Cia')
newString('P. Benitez')
newString('Pedro Estevez')
newString('Pedro Martin')
newString('Penamil')
newString('Penguin')
newString('Pensadores')
newString('Pera')
newString('Perdomo')
newString('Perez')
newString('Perez-Carrillo')
newString('Perfecci\xc3\xb3n')
newString('Perfect Cut')
newString('Perfecto Garcia')
newString('Pergamino')
newString('Perique')
newString('Perla del Mar')
newString('Personales')
newString('Peterson')
newString('Peter Stokkebye')
newString('Petri')
newString('Petrus')
newString('Phatash')
newString('Pheasant')
newString('Phil')
newString('Phillies')
newString('Phillipine Cigar Company')
newString('Phillips &amp; King')
newString('Philosophy')
newString('Picasso')
newString('Pickwick')
newString('Pigtail')
newString('Piloto Cubano')
newString('Pinar')
newString('Pinar del Rio')
newString('Pinar de Oro')
newString('Pinnacle')
newString('Pintor')
newString('PIO')
newString('Pioneer Valley')
newString('Pipers Haven')
newString('Pirata')
newString('Pirate&#39;s Gold')
newString('Pitbull Puros')
newString('P.L.')
newString('Placeres')
newString('Plasencia')
newString('Playboy by Altadis')
newString('Playboy by Don Diego')
newString('Players Club')
newString('PLC')
newString('Pleiades')
newString('Poderozo')
newString('Ponderables')
newString('Pontalba')
newString('Por Larranaga')
newString('Por Larranaga (Cuban)')
newString('Por Matamor')
newString('Porto Bello')
newString('Porto Real (Felipe Gregorio)')
newString('Port Royal')
newString('Potente')
newString('Praderas')
newString('Premier')
newString('Premium')
newString('Premium Blend Cigars')
newString('Premium Cuban')
newString('Premium Dominicana')
newString('Premium Selection (by Kristoff)')
newString('Premium Value')
newString('President&#39;s Private Stock')
newString('Prestige (Mike&#39;s Cigars)')
newString('Presumidos (Thompson)')
newString('Prida')
newString('Pride')
newString('Pride of Copan')
newString('Pride of Jamaica')
newString('Pride of Panama')
newString('Primal (JR Cigars)')
newString('Primera de Honduras')
newString('Primera de Nicaragua')
newString('Primero de Fabrica')
newString('Primeros')
newString('Prime Time')
newString('Primo de Cuba')
newString('Primo del Cristo')
newString('Primo del Rey')
newString('Primos (Blanco)')
newString('PrimoStogies.com')
newString('Prince Albert')
newString('Principes (by La Aurora)')
newString('Private Stock')
newString('Profesor Sila')
newString('Profile (by Cult)')
newString('Providencia')
newString('Pryme')
newString('Pueblo Dominicano')
newString('Punch')
newString('Punch (Cuban)')
newString('Pura Experiencia')
newString('Pura Soul')
newString('Purisco')
newString('Puritos')
newString('Puritos Cossa Nostra')
newString('Puroexpress')
newString('Purofino')
newString('Puro Nicaragua')
newString('Puro Placer')
newString('Puro Sabor')
newString('Puros del Ibera')
newString('Puros Don Abreu')
newString('Puros Huerfanos')
newString('Puros Indios')
newString('Puros Irene')
newString('Puros Morgan')
newString('Puros Nirvana')
newString('Puros of St James')
newString('Puros Passionados')
newString('Puros Polanco')
newString('Puros Reales')
newString('Puros Reynoso')
newString('Puros Tejera')
newString('Puro Venezolano')
newString('Pyramid')
newString('Pyro')
newString('Flor De Gonzalez')
newString('Q-ban Fuerte')
newString('QE2')
newString('Q&#39;Oro')
newString('QQ')
newString('Quadrado')
newString('Quai d&#39;Orsay')
newString('Queen City')
newString('Quesada')
newString('Quetzal (Dom)')
newString('Quetzal (Hon)')
newString('Quintero')
newString('Quintero (Cuban) (Quintero y Hermano)')
newString('Quintessa')
newString('Quirantes')
newString('Quisqueya')
newString('Quisqueyana')
newString('Quorum')
newString('Quo Vadimus')
newString('RA')
newString('Racine &amp; Laramie')
newString('Rafael')
newString('Rafael Gonzalez')
newString('Rafael Gonzalez (Cuban)')
newString('Rafaeli&#39;s')
newString('Raices Cubanas')
newString('Raji&#39;s Untimely Demise')
newString('Ramayana')
newString('Rambling River')
newString('Ramon Allones')
newString('Ramon Allones (Cuban)')
newString('Ramon Bueso')
newString('Ramondo')
newString('Ramon y Ramon')
newString('Ramrod')
newString('Ram Rod')
newString('Rancho Dominicano')
newString('Rancho Real')
newString('Randello')
newString('Randello X')
newString('Rapture (by Viva Republica)')
newString('Rav')
newString('R. A. Villamil')
newString('RB Fundadores')
newString('Real Cuban Knock-Offs')
newString('Real Men Smoke Cigars')
newString('Real Morenos')
newString('Reas')
newString('Rebellious')
newString('Recon')
newString('Red Buck')
newString('Red Dot')
newString('Redencion')
newString('Red Head')
newString('Redlands')
newString('Red Lion')
newString('Reel Grande')
newString('Regalo')
newString('Regalos')
newString('Regius')
newString('Reina de Manilla')
newString('Reinado')
newString('Relajado')
newString('Reloba')
newString('Remedios')
newString('Remington')
newString('Reo')
newString('Repeater')
newString('Reposado 96')
newString('Republica Dominican')
newString('Reserva Cristobal')
newString('Reserva de Inexpensivo')
newString('Reserva Dorada')
newString('Reserva Ligadora')
newString('Reserva Limitada')
newString('Reserva No. 464')
newString('Reserva President\xc3\xa8')
newString('Re+United (Foundry Tobacco Company)')
newString('Revolucion')
newString('Rex Britannia')
newString('Rey Alfonso')
newString('Rey de Reyes (European)')
newString('Rey de Reyes (Miami Cigar Co.)')
newString('Rey de Reyes (Rolando Reyes)')
newString('Rey de Zaba')
newString('Reyes Family')
newString('Reyes y Benicio')
newString('Rey Miguel')
newString('Reynaldo')
newString('R.G. Santiago')
newString('R. G. Tobacco')
newString('Rhum (Ted&#39;s Cigars)')
newString('Riata')
newString('Rical')
newString('Ricardo')
newString('Richard Nixon')
newString('Richards')
newString('Richwood')
newString('Rico Havana')
newString('Ricos Dominicanos')
newString('Rigoletto')
newString('Rima')
newString('Rio de Cuba')
newString('Rio Mayos')
newString('Rio Tabac &quot;R&quot;')
newString('Riot Cigars (Stogie Boys)')
newString('Rising Sun')
newString('Ritmeester')
newString('Ritz Square')
newString('Rivalo')
newString('Robali')
newString('Robert Burns')
newString('Roberto')
newString('Roberto P. Duran')
newString('Robert Small Little Cigars')
newString('Roble Viejo')
newString('Rocco Gaetano d&#39;Angelo')
newString('Rochesterville 1831')
newString('Rock-A-Feller (by International Tobacco Partners)')
newString('Rocky Patel')
newString('Rodrigo')
newString('Rodrigo de Xerex')
newString('Rodriguez')
newString('Rodriguez &amp; Menendez')
newString('Roger Jacobi Cigars')
newString('Roll Back (C&amp;C Cigars)')
newString('Roller&#39;s Choice')
newString('Roly')
newString('RoMa Craft Tobac')
newString('RoMa Craft Tobac &amp; Blue Havana')
newString('Romana')
newString('Romanticos')
newString('Romeo y Julieta')
newString('Romeo y Julieta (Cuban)')
newString('Ron Mexico')
newString('Rons')
newString('Ron&#39;s Cigars')
newString('Room 101')
newString('Roro Mendut')
newString('Rosa Cuba')
newString('Rosalones (by Joya de Nicaragua)')
newString('Rosalones (MATASA)')
newString('Rosario Cigars')
newString('Roughneck')
newString('Rough Rider Sweets')
newString('Roxor')
newString('Royal Barbados')
newString('Royal Blunt')
newString('Royal Comodore Jamaica')
newString('Royal Danisg Cigars')
newString('Royal Danish Cigars')
newString('Royal Dominicana')
newString('Royales')
newString('Royal Estates')
newString('Royal Flavor')
newString('Royal Gold')
newString('Royal Hawaiian')
newString('Royal Honduras')
newString('Royal Jamaica')
newString('Royal Jamaica (Pre-Hurricane Gilbert)')
newString('Royal Manna')
newString('Royal Silk')
newString('Rubirosa')
newString('Rumba')
newString('Rum Runner')
newString('Rushmore')
newString('Rustico Habano')
newString('Rusty Humphries')
newString('Rusty&#39;s')
newString('Ruy Lopez')
newString('Ryan Danger')
newString('Sabana')
newString('Sabor Cubano (by La Tradicion Cubana)')
newString('Sabor Habano')
newString('Sabroso')
newString('SACUBA')
newString('Saga')
newString('Saint Luis Rey')
newString('Saint Luis Rey (Cuban)')
newString('Salute to Arms')
newString('Salvador')
newString('Samana')
newString('Sam Leccia Cigar Co.')
newString('Samsara')
newString('San Angelo')
newString('San Antonio')
newString('San Bajito')
newString('San Carlos')
newString('Sancho Panza')
newString('Sancho Panza (Cuban)')
newString('San Cristobal')
newString('San Cristobal de La Habana')
newString('Sancti Spiritus')
newString('Sandes')
newString('San Felice')
newString('San Fernando')
newString('Sanj&#39;s Smoke Shop')
newString('San Juan Martinez')
newString('San Luis Rey')
newString('San Marco')
newString('San Martin')
newString('San Miguel (Gurkha San Miguel)')
newString('San Miguel y Ramirez')
newString('San Pedro Cubana')
newString('Santa Ana')
newString('Santa Clara')
newString('Santa Cruz (Canary Islands)')
newString('Santa Cruz (Jamaica)')
newString('Santa Damiana')
newString('Santa Fe')
newString('Santa Julia')
newString('Santa Karina')
newString('Santamaria')
newString('Santa Rosa')
newString('Santiago')
newString('Santiago Cabana')
newString('Santiago Cigar Factory')
newString('Santiago de los Caballeros')
newString('Santiago (Dominican)')
newString('Santiago Silk')
newString('Santo Diego')
newString('San Vicente Collection')
newString('San Victor')
newString('Sao Salvador')
newString('Savannah Bulldogs')
newString('Savinelli')
newString('Savoy')
newString('SBK (Small Batch Kings)')
newString('SB (Stogie Boys)')
newString('Scarface')
newString('Schimmelpenninck')
newString('Schrader Hispaniola')
newString('Schwartz &amp; Fenaoui')
newString('Sebastian Reservas')
newString('Second Growth')
newString('Secret Blend of Cuba')
newString('Segovia')
newString('Segundos')
newString('Seijas')
newString('Seleccion Privada (DR)')
newString('Seleccion Privada (NIC)')
newString('Selecto Puro Dominicano')
newString('Sello de Oro')
newString('Semar')
newString('Semper Fi')
newString('Sencillo')
newString('Seneca')
newString('Se\xc3\xb1or Bonilla')
newString('Se\xc3\xb1or David')
newString('Senorial by Jose Blanco (Las Cumbres Tabaco)')
newString('Se\xc3\xb1or San Andres')
newString('Senor Solomon')
newString('Serafin de Cuba')
newString('Series X')
newString('Serrano')
newString('Sevilla')
newString('Sevillana (Caldwell Cigars)')
newString('Sex on the Beach')
newString('Shaggys')
newString('Shakespeare')
newString('Shaman')
newString('Shane Old Fashioned')
newString('Shangri La')
newString('SHB')
newString('Shrapnel')
newString('Siboney')
newString('Siboney (Cuban)')
newString('SIG')
newString('Siglo 21')
newString('Siglo Limited Reserve')
newString('Signature Collection')
newString('Signature House Blend')
newString('Signature Stogie')
newString('Signet')
newString('Signoria (by Felipe Gregorio)')
newString('Silo Cigars')
newString('Silverdale')
newString('Simonoff')
newString('Simpatico')
newString('Sinatra')
newString('Sindicato Cigars')
newString('Sir Vin Cigars')
newString('Six Zero')
newString('Smok-a-Cuba')
newString('Smoke Inn')
newString('Smoker Friendly')
newString('Smoker&#39;s Best')
newString('Smokers Choice')
newString('Smokin&#39;')
newString('Smoking Jacket Cigars (by Hendrik Kelner Jr.)')
newString('Smokin Joes')
newString('Smokin&#39; Sandwich')
newString('Smokin&#39; Tiger')
newString('Smokin&#39; Toad')
newString('Smokin&#39; World')
newString('S.O.B Cigar')
newString('Socorro')
newString('SoEx')
newString('Solamente')
newString('Sol Cubano')
newString('Soldado Americano')
newString('Sol de Cuba')
newString('Soleares')
newString('Soledad')
newString('Solo Aroma')
newString('Solo Aroma de Esteli')
newString('Solo Cafe')
newString('Sol y Mar')
newString('Sombrio Deseo')
newString('Sonador (Thompson)')
newString('Soneros (Cubanacan)')
newString('Sorullos')
newString('Sosa')
newString('Sotolongo')
newString('South Beach')
newString('South Beach Flavors')
newString('Spag &amp; Co.')
newString('Spanish Galleon')
newString('Spanish Heirloom')
newString('Spanish Honduran')
newString('Spartacus')
newString('SPC')
newString('Speakeasy')
newString('Special Blends by Alec Bradley')
newString('Special Blends (by H.Kelner)')
newString('Special Caribbeans')
newString('Special Jamaican')
newString('Spectre (by A.J. Fernandez)')
newString('Spirit of Art (Cuba Rica Tabacalera)')
newString('S. Plasencia Premium')
newString('Sportsman&#39;s Reserve')
newString('Stag')
newString('Stanislaw')
newString('St. Croix')
newString('S.T. Dupont')
newString('Steel City Cigarillos')
newString('Stefano')
newString('St George')
newString('Stock 10/1')
newString('Stogie Castillo')
newString('Stogies on Grand')
newString('Stradivarius')
newString('Strelsky')
newString('Studio Tabac (by Oliva)')
newString('Sturgis')
newString('Sturgis Smoke')
newString('Suarez')
newString('Suave')
newString('Sublimes')
newString('Suenos Oro')
newString('Suerdieck')
newString('Sultan')
newString('Sultan Cigars')
newString('Summus')
newString('Sun Ripened Oscuros')
newString('Sunrise Reserve')
newString('Sunset of Key West')
newString('SuperiorCigars.com')
newString('Superiores')
newString('Super Premium')
newString('Super Value')
newString('Supervisor Selection By Alec Bradley')
newString('Supreme Blend')
newString('Supre Sweets')
newString('Surrogates (L&#39;Atelier)')
newString('Svenska Tobaksbolaget')
newString('SWAG')
newString('Sweet Aromas by Macabi')
newString('Sweet Daddies')
newString('Sweeteez')
newString('Sweet Nostalgia')
newString('Swigar')
newString('Swisher')
newString('Tabacalera')
newString('Tabacalera Esteli')
newString('Tabacalera Leyendas Cubanas')
newString('Tabacalera y Familia')
newString('Tabacalera Zapata')
newString('Tabacales del Sur')
newString('Tabacconist Choice')
newString('Tabaco Ramones')
newString('Tabacos Bandoleros')
newString('Tabacos de Costa Rica')
newString('Tabac Ramones')
newString('Tabamex')
newString('Tabanero')
newString('Tabantillas')
newString('Table 36')
newString('Taboo')
newString('TACASA')
newString('Taino')
newString('Tambo')
newString('Tambor')
newString('Tamboril')
newString('Tampa Nugget')
newString('Tampa Sweet')
newString('Tampa Tobacco Company')
newString('Tampa Trolleys')
newString('Tampa Tropics')
newString('Tarazona')
newString('Tarpon Sponger')
newString('Tatiana')
newString('Tatuaje')
newString('Te-Amo')
newString('Tea Party Cigar')
newString('Ted&#39;s Cigars')
newString('Temple Hall')
newString('Tena y Vega')
newString('Tennessee Waltz (Crowned Heads)')
newString('Tenorio')
newString('Tesa Cigar Co.')
newString('Tesa Colores')
newString('Tesoro')
newString('Tesoros Cubanos')
newString('Tesshu Tobac')
newString('Texana')
newString('The Angel&#39;s Anvil (Crowned Heads)')
newString('The Brick (by Carlos Torano)')
newString('The Churchill Cigar')
newString('The Cigar (Perdomo)')
newString('The Don')
newString('The Drake')
newString('The Famous Rum Runner')
newString('The Flava')
newString('The Football Cigar')
newString('The Good, Bad &amp; Ugly')
newString('The King Is Dead (Caldwell Collection)')
newString('The Log')
newString('The Original Key West Cigar Factory')
newString('The Smokin` Cigar Inc.')
newString('The Thin Blue Line')
newString('Third Millenium')
newString('Thomas Hinds')
newString('Thomas Jefferson Deuces')
newString('Thompson')
newString('Thunder by Nimish')
newString('Thurman Thomas')
newString('Tia Martia')
newString('Tiburon')
newString('Tico')
newString('Tierra del Sol (by Perdomo)')
newString('Tierra Volcan (Mombacho)')
newString('Tijerinos')
newString('Tijuana Smalls')
newString('Timbuctoo')
newString('Timothy&#39;s Fine Tobaccos')
newString('Tinder Box')
newString('Tio Pepe')
newString('Tiparillo')
newString('T.L. Johnson')
newString('T. Mercedes')
newString('T.N.J. Smokin&#39; Spirits')
newString('TNT')
newString('Tobacanary')
newString('Tobacco Factory (Evan&#39;s Tobacco Factory)')
newString('Tobacco Haven')
newString('Tobacconist Choice')
newString('Tobaco Nacional')
newString('Tobajara')
newString('Tony Alvarez')
newString('Top Cigars')
newString('Top Hat')
newString('T.O.P.I.C. (Tobacco Outlet Premium Cigars)')
newString('Topper')
newString('Topstone')
newString('Torano')
newString('Torcedor')
newString('Torcido')
newString('Toro Bravo')
newString('Toro de Oro')
newString('Toros')
newString('Toro y Leon')
newString('Torquino')
newString('Torres')
newString('Tortuga')
newString('Tosa')
newString('Toscano')
newString('Total Flame')
newString('T&amp;P (Guatemala)')
newString('Trabuco')
newString('Trader Jack&#39;s')
newString('Trader&#39;s Reserve')
newString('Tranquilo')
newString('Treasures of Costa Rica')
newString('Tresado')
newString('Tres Anos Dominican')
newString('Tre Sigari')
newString('Trichinopoly')
newString('Trinidad')
newString('Trinidad (Cuban)')
newString('Trinidad y Cia')
newString('Trinidad y Hermano')
newString('Triple Harp')
newString('Trocadero')
newString('Tropical Fever')
newString('Tropical Republic')
newString('Troya')
newString('Troya (Cuban)')
newString('True Blunt')
newString('Tueros')
newString('Tulas')
newString('Turei')
newString('Turks Select')
newString('Twinkle')
newString('Two-Tone')
newString('Ugly Coyote')
newString('Uhle Tobacco Company')
newString('Unbanded Cigars.com')
newString('Uncle Sam')
newString('United Cigar')
newString('Urbano')
newString('Urs Portmann')
newString('Valencia')
newString('Valentia')
newString('Valeroso')
newString('Vallarta Cigar Factory')
newString('Valle de la Iguana')
newString('Valle Dorado')
newString('Valle Grande')
newString('Vallejuelo')
newString('Vamma Del Sol')
newString('Van der Donk')
newString('Van &#39;t Veen')
newString('Vaquero')
newString('Vargas')
newString('Varina Farms')
newString('Vartan')
newString('Vasco da Gama')
newString('Vato')
newString('V Centennial (Tropical Tobacco)')
newString('Vega del Rey')
newString('Vega del Tader')
newString('Vega Fina (DR)')
newString('Vega Fina (Sp)')
newString('Vega Palmera')
newString('Vega Real')
newString('Vegas de Fonseca')
newString('Vegas de Nicaragua')
newString('Vegas de Santiago')
newString('Vegas de Tabacalera Esteli')
newString('Vegas Robaina')
newString('Vega Talanga')
newString('Vegueros')
newString('Velasquez')
newString('Velvet Cigars')
newString('Vendetta')
newString('Vengeance')
newString('Venom')
newString('Ventura Cigar')
newString('Veracruz')
newString('Verdadero')
newString('Verellen')
newString('Veritas')
newString('Verona')
newString('Verona (Egypt)')
newString('Viaje')
newString('Vibe')
newString('Vicarias (Tre-J Cigars)')
newString('Victor Calvo')
newString('Victor de La Cruz')
newString('Victoria')
newString('Victorino')
newString('Victor Sinclair')
newString('Victory')
newString('Vieja Hacienda')
newString('Vieja Tradicion')
newString('Vigilante')
newString('Viking Village')
newString('Villa')
newString('Villa de Cuba')
newString('Villa Dominicana')
newString('Villa Havana')
newString('Villar y Villar')
newString('Villa Zamorano (Maya Selva)')
newString('Villazon Hatsa')
newString('Villega Reales')
newString('Villiger')
newString('Vindicator')
newString('Vintage Especial (by Plasencia)')
newString('VIP (by George Rico)')
newString('Virtuoso')
newString('Vista de Cuba (Oliveros)')
newString('Viva Bandito')
newString('Vivaldi')
newString('Vivalo')
newString('Viva Republica')
newString('VMI')
newString('V. M. Santana')
newString('Vogel')
newString('Voila')
newString('VSOP')
newString('Vudu')
newString('Vuelta Abajo')
newString('Vueltabajo')
newString('Waller &amp; Bengtsson')
newString('Warlock')
newString('Warped')
newString('Washington')
newString('WB Brand')
newString('W&amp;D')
newString('W.D.&amp; H.O.Wills')
newString('Wellington Cigar Factory')
newString('West Indies')
newString('West Indies Cigar CO')
newString('Westminster')
newString('We The People (Marcus Daniel)')
newString('W. F. Mild (Finck)')
newString('What&#39;s Knot to Love')
newString('White Buffalo')
newString('White Cat')
newString('White Horse (Felipe Gregorio)')
newString('White House')
newString('White Owl')
newString('White Star')
newString('Widow&#39;s Son (Connecticut Valley Tobacconist)')
newString('Wilde')
newString('Willem II')
newString('William Penn')
newString('William Ventura')
newString('Willy Cigars')
newString('Wilson Adams')
newString('Winchester')
newString('Windsor')
newString('Winston Churchill (Davidoff)')
newString('Wintermann')
newString('Wintersmokes')
newString('Winthrop')
newString('Wise Guys')
newString('Wismilak')
newString('Wm. Ascot')
newString('Wolf Brothers')
newString('WTF Cigars')
newString('Wynwood')
newString('Xerez')
newString('xikar')
newString('Xing')
newString('X-Rated')
newString('XXO')
newString('Yago')
newString('Yankee Clipper')
newString('Yaquiba (Haiti)')
newString('Y.B.')
newString('Ybor Cigars Plus')
newString('Ybor Gold')
newString('Yellow Band')
newString('Ynego Montoya')
newString('Yumuri')
newString('Zahi')
newString('Zelo de Cuba')
newString('Zemis')
newString('Zengotita')
newString('Zeus (Corona Cigar Co.)')
newString('Z-Gar')
newString('Zigari')
newString('Zino')
newString('Ziq')
newString('Zoidian')
newString('Oscar Valladares Tobacco')